- cmake.py
- runner/nios2.py
CC: @ramakrishnapallala 
These west fixes should address zephyrproject-rtos/zephyr#7954 and zephyrproject-rtos/zephyr#7927.
(Note west is now developed in its own tree, with code moving to Zephyr from here.)
> Misc fixes

- cmake.py
- runner/nios2.py
- runner/nrfjprog.py
This is based on #1 to make merging easier. Just the final commit is what matters.
Straightfoward port of https://github.com/zephyrproject-rtos/zephyr/pull/6809 to west.
CC: @SebastianBoe, @nvlsianpu
> Nrfjprog: add --erase

- src/west/_bootstrap/main.py
- src/west/commands/build.py
- src/west/commands/project.py
- src/west/main.py
- src/west/util.py
> Fixes 0.2.0rc2

- README.rst
- src/west/_bootstrap/version.py
I'm not aware of any filed or unfiled blockers -- proposing we are go for rc3. Hopefully this is the last one before 0.2.0 and wider testing.
> West 0.2.0rc3

- README.rst
- src/west/_bootstrap/version.py
Set the release version, and remove the rc tags from the README.
> West 0.2.0

- src/west/main.py
> west: main: don't swallow Exception

- src/west/commands/project.py
If either the west or the manifest repository has local modifications,
skip automatically updating the modified repository, with a warning.
This avoids merge conflicts when working on them.
Maybe the manifest repository update could be skipped if the west
repository is out of date, and vice versa, but I suspect this version
might be good enough.
@ulfalizer please check if the issues below are addressed indeed.
Fixes #62 
Fixes #59
> commands: project: Only update west/manifest via fast-forward

- README.rst
- scripts/west-completion.bash
- src/west/_bootstrap/main.py
- src/west/commands/build.py
- src/west/commands/run_common.py
- src/west/main.py
Currently completes flags and subcommand names.
Fixes: #24
> Add Bash auto-completion script

- src/west/runners/intel_s1000.py
This reverts commit bc7b1c595ed4090be6d80859a01a0bb372ae030c in
the zephyr main tree to fix the runner script and also does the
below modifications.
1) explicitly terminate processes.
2) implicitly call debugserver when debug is called.
Signed-off-by: Rajavardhan Gundi <rajavardhan.gundi@intel.com>
> intel_s1000: scripts: Fix the runner script

- src/west/commands/project.py
Fixes: #119
This commit changes the way show-ref is executed in order to determine
whether HEAD is pointing to a valid reference or if the repository is
in initialized stated.
As discussed on IRC, and described in #119, `git show-ref --quiet --verify HEAD` unexpectedly returns 1 on git version 2.7.4 and probably others.
This PR changes the command into:
`git show-ref --quiet --head <random-64bytes>`
as that returns 0 if `head` is valid and 1 if `head` is not a valid reference. 
Random 64 bytes is used to avoid the reference to match a valid tag or branch.
> git: Updating use of show-ref to work with older git versions

- README.rst
- src/west/_bootstrap/version.py
> West 0.4.0rc1

- src/west/commands/build.py
Improve  the `west build -h` output.
> commands: build: improve command line help

- src/west/runners/__init__.py
- src/west/runners/blackmagicprobe.py
- tests/west/runners/test_imports.py
Based on https://github.com/zephyrproject-rtos/zephyr/pull/6829 by @diytronic, updated and added
debug and attach commands.
> runners: Black Magic Probe runner

- src/west/runners/blackmagicprobe.py
Renames kernel_elf to elf_file, and handles cases where
it is not specified.
Signed-off-by: Tavish Naruka <tavishnaruka@gmail.com>
> runners: blackmagicprobe: fix refrence to kernel_*

- src/west/main.py
- tests/west/project/test_project.py
When playing with extension commands, two things were noticed:
1) Same command can be defined in multiple projects
2) When multiple projects are defining extension commands, they show up inside each others lists.
```
external commands from project Kconfiglib at path "subdir/Kconfiglib":
kconfigtest
test
external commands from project Kconfiglib at path "net-tools":
kconfigtest
test
```
This commit fixes:
- Issue if multiple projects defines the same command.
This will print a warning for project/command not being available
- Fixed issue where same command could be listed multiple times
Note: doesn't rebase on top of pr/156, looking into that.
> extension command: Fixing issue with extension command duplication

- src/west/_bootstrap/main.py
This is a follow up PR to pr/162.
Main update is to remove the second `fetch`
Fetching the normal ref-space in first fetch also allows to checkout tags while still keep a reference to the tag name.
This means that when specifying a tag, users will now see, as example:
```
HEAD detached at v0.3.0
```
instead of:
```
HEAD detached at FETCH_HEAD
```
It also allows users to specify a SHA as revision.
edit: Also added `-C <dest>` as the change dir in pr/162 actually broke the directory arg.
> bootstrap: Removed second fetch and allow for SHA

- src/west/_bootstrap/main.py
- src/west/commands/project.py
- src/west/main.py
- src/west/manifest.py
- src/west/util.py
- tests/west/project/test_project.py
> Add manifest command

- src/west/_bootstrap/version.py
Just queueing this up so we can merge when ready. I think we ought to get https://github.com/zephyrproject-rtos/west/pull/192 in first before we cut this point release, though.
> West v0.5.3

- src/west/main.py
On Windows execv() is asynchronous, leading to an additional
shell being open concurrently with the existing one.
Use Popen() instead, which ensure synchronicity across all
operating systems.
https://bugs.python.org/issue9148
https://bugs.python.org/issue19124
> main: Use Popen() + exit instead of execv()

- scripts/west-completion.bash
Update the list of commands and their flags so that the bash completion
is actually useful.
> scripts: Update bash completion to match current set

- src/west/commands/project.py
- src/west/main.py
- src/west/manifest.py
This PR fixes #214 .
During the fix issue #218 was discovered and has been fix in separate commit.
> Issue 214 & 218.  init with self.path missing and westconfig settings in ~/.westconfig

- src/west/commands/project.py
- src/west/main.py
As discussed on slack.
Default order is:
1) `--zephyr-base` on cmd line
2) Environment setting, `ZEPHYR_BASE`
3) Config file setting. Config file is now written with `zephyr-base` during init, and on `self-update` if missing
This commit changes the order of precedence so that environment setting
takes precedence over west config option.
It also introduces a new config file setting, to allow to specify which
setting: `environment` or `configfile` that will take precedence.
To simplify search for ZEPHYR_BASE, this setting will now be written to
the local .west/config during init and selfupdate, if non-existing.
> zephyr-base: ZEPHYR_BASE env takes precedence over config settings

- src/west/_bootstrap/main.py
- src/west/_bootstrap/version.py
- src/west/backports.py
- src/west/commands/project.py
- src/west/manifest.py
This PR fixes usability issues with west's multi-repo command output.
> Fix up multirepo command output

- README.rst
> README: fix link to docs

- src/west/commands/project.py
Depends on #290, fixes #274
```
By default, skip fetches of revisions that resolve to SHAs or tag
names that are already available locally.
The user can override by using west update -f always.
```
CC: @pabigot
> Fetch optimization

- src/west/commands/config.py
- src/west/configuration.py
- src/west/manifest.py
- tests/manifests/invalid_no_project_named_manifest.yml
- tests/test_config.py
- tests/test_manifest.py
- tests/test_project.py
- tox.ini
Sorry this took too long, but there were more edge cases than my original optimism accounted for.
These are the changes we need to finish the downstream NCS extension commands to list out of tree patches, etc. I want to finish the implementations of the downstream commands before we merge this, though, so marking DNM.
> Path handling improvements

- src/west/main.py
- tests/conftest.py
- tests/test_help.py
- tests/test_project.py
The first and last commit contain the real fixes. The intermediate ones are just cosmetics.
> Fix extension help

- src/west/log.py
- src/west/manifest.py
- src/west/version.py
A couple of additional patches which are useful upstream in general, and in particular are needed to make downstream extensions work.
> Ncs extension additions

- src/west/commands/project.py
Cherry-pick a fix from 0.6.2 into master.
> commands: west update: fix fetch optimization

- src/west/commands/project.py
- tests/conftest.py
- tests/test_project.py
I thought we had coverage for this, but I was wrong, and of course that means it doesn't work. Fix support for the feature and fix the tests.
> Fix project clone depths

- src/west/configuration.py
@E3V3A can you confirm this is a fix for you? It's as discussed in the issue you raised.
Fixes: #300
> configuration: add cygwin handling for the system config file

- src/west/cmake.py
Resolves issue reported in #322
> resolved UTF-8 encoding issue in CMakeCache, closes #322

- setup.py
- src/west/build.py
- src/west/cmake.py
- src/west/commands/__init__.py
- src/west/commands/project.py
- src/west/configuration.py
- src/west/log.py
- src/west/main.py
- src/west/manifest-schema.yml
- src/west/manifest.py
- src/west/util.py
- tests/test_help.py
- tests/test_manifest.py
- tox.ini
Depends on https://github.com/zephyrproject-rtos/west/pull/324
Just some random cleanups I had time to do while working on #221
> Misc cleanups

- src/west/commands/project.py
> west init: print git commands at -v -v verbosity

- src/west/commands/project.py
- src/west/manifest.py
- tests/test_manifest.py
- tests/test_project.py
@carlescufi these are the first patches in my manifest imports queue.
I'd like to get them in now so you can work on git submodules support using the updated Project API, so we don't have to rebase on top of each other.
> Project rework

- src/west/main.py
- tests/test_help.py
- tests/test_manifest.py
- tests/test_project.py
Plus one patch related to help printing that I noticed while getting the tests passing on windows.
> Windows fixes

- src/west/commands/__init__.py
- src/west/commands/project.py
- src/west/main.py
- src/west/manifest.py
- tests/test_help.py
- tests/test_manifest.py
- tests/test_project.py
A collection of prep-work commits I've written as part of the manifest imports work that aren't directly related to the feature, but I would like to get tested in CI, reviewed, and hopefully merged, as I think they're OK to go in on their own.
> Grab bag of fixes and changes

- src/west/commands/project.py
- src/west/manifest.py
@carlescufi @tejlmand would you mind taking a look?
This is the last loose end that I realized I needed to implement before we can cut the beta for west manifest imports.
> west manifest --resolve

- src/west/manifest.py
- tests/test_manifest.py
This completes the feature set for west manifest imports. We include a
test of name whitelists from the documentation as a basic sanity
check. Further testing is left to future work.
To close out this feature after this, we should only need more error
handling and testing. In particular, beyond general coverage issues,
we need to try to reject any obvious import cycles, and add tests for
the same.
> manifest: support maps of imports

- src/west/app/main.py
- src/west/app/project.py
- src/west/manifest.py
- tests/test_manifest.py
More fixes and cleanups for the manifest library, mostly related to imports.
Fixes #360
> Manifest fixes

- .github/workflows/test.yml
Introduce a github action that will run tox on a number of python
versions and host OSes for testing.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> github: Use a github action for testing

- tests/conftest.py
- tests/test_manifest.py
- tests/test_project.py
Add some more regression tests.
> More import tests

- src/west/app/project.py
This prints performance statistics. Zephyr wants it for figuring out
slowdowns observed in CI.
> west update: add --stats option

- .github/workflows/test.yml
- .gitignore
- src/west/app/project.py
- src/west/manifest.py
- src/west/version.py
- tests/conftest.py
Get the tests passing on Windows and macOS, and cherry-pick https://github.com/zephyrproject-rtos/west/pull/369 so we can merge it with CI green.
> Bug fixes + rc2

- MAINTAINERS.rst
I've collected lessons learned from past releases in this file. We can use it going forward as a basis for continuing improvements to our release process.
> Add MAINTAINERS.rst

- MAINTAINERS.rst
- src/west/app/project.py
- src/west/manifest.py
This backports the latest master branch commits into 0.7. None of them are scary and there are good fixes in here targeted for the 0.7.2 milestone.
> 0.7 backports from master

- src/west/commands.py
- src/west/manifest.py
- tests/test_manifest.py
Following https://github.com/zephyrproject-rtos/west/commit/26b69f987e2715a69e789c214d40d51eee277a7b, let's add type annotations for manifest.py, which I think is west's most important module.
Fix a few issues caught by mypy before doing so. Also do some clean-ups and refactors before adding type annotations to make the results more pleasant.
> More typing

- src/west/app/project.py
- tests/test_project.py
This should come from the manifest.path configuration option, which
may disagree with "self: path:" in the manifest file itself.
Add a --manifest-path-from-yml option as a chicken bit to keep the old
behavior in case anybody is relying on it.
Fixes: #420
> west list: fix manifest path

- src/west/manifest.py
While we were working on adding typing annotations, I was unaware that
typing.NamedTuple existed and did not use it.  This is a more
convenient alternative to collections.namedtuple since it provides
type checking for fields in the relevant tuples. Switch to it.
Suggested-by: Carles Cufí <carles.cufi@nordicsemi.no>
> manifest: use typing.NamedTuple

- README.rst
- src/west/app/main.py
- src/west/app/project.py
- src/west/manifest.py
- tests/test_project.py
> add support for manifest filenames other than west.yml

- MAINTAINERS.rst
Just some cleanups and clarifications on how I'd like to do this going
forward. The main clarifications are around SCHEMA_VERSION, since this
is changing in 0.8 and I want to make sure we're all on the same page.
> MAINTAINERS.rst: cleanups, clarifications

- src/west/version.py
> [v0.8-branch] West v0.8.0a1

- src/west/version.py
Maureen asked us to hold off on this until after Zephyr 2.4.0. @carlescufi I held off yesterday since I saw you were off, but I realized you are still off now. I think we should just go ahead and release this, @tejlmand .
> West v0.8.0

- .github/workflows/test.yml
- tests/conftest.py
- tests/test_config.py
- tests/test_help.py
- tests/test_main.py
- tests/test_manifest.py
- tests/test_project.py
- tox.ini
Miscellaneous commits related to testing.
> Test changes

- tests/conftest.py
- tests/test_manifest.py
- tests/test_project.py
Looking at the users, the better default is clearly True.
> tests: change create_workspace and_git kwarg default

- src/west/__init__.py
- src/west/manifest.py
- src/west/version.py
- tests/test_manifest.py
- bug fix backports from #482 
- warn on combination of import and group filter
> West 0.9.1a1

- src/west/app/project.py
- src/west/commands.py
This makes it easier for commands to check the git version.
> Move git checks to WestCommand

- src/west/commands.py
- src/west/configuration.py
- tests/test_config.py
Miscellaneous standalone improvements I ran into while working on something else.
> Misc. improvements

- MAINTAINERS.rst
Updates for clarity and to match current practice.
Reflect some practical changes that I've been doing in the past couple
of release that cut down on review latency once it's been agreed that
it's release time. In particular, we are cutting out the review cycles
for forking the release branch, changing the versions, and tagging the
main branch after it's moved from the release branch.
Rework the section in to step 1-2-3 style while we're here, to make it
easier to follow along with.
> MAINTAINERS.rst: update 'cutting a release branch'

- src/west/configuration.py
It's pretty much like Cygwin as far as these things go, so
do the same things.
> Support the MSYS2 platform

- src/west/manifest.py
> manifest.py: fix docstring

- src/west/app/main.py
- src/west/commands.py
Two fixes for how we handle extensions. See individual commit logs for details.
> Extension error handling fixes

- tests/test_project.py
Test that west leaves the local repo alone when HEAD~0 is used.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
> test_project.py: Add test for using "revision: HEAD~0" in manifests

- MAINTAINERS.rst
- README.rst
> README: updates

- src/west/app/main.py
We shouldn't be exiting 0 on interrupt, because this means we did not successfully complete. Use better platform-specific exception handling instead. See comments for details.
Fixes: #636
> app: fix control-C behavior

- src/west/app/project.py
Fixes: #650
A few concerns have been voiced about the west compare output:
1. its signal:noise ratio is too low (too many lines per
project without enough useful information per line)
2. the end of the status output from one project is hard to
separate from the status output for the next
3. it isn't obvious enough whether HEAD == manifest-rev or not
To try to resolve 2. without making 1. any worse, explicitly print
HEAD and manifest-rev if they differ, without adding any extra lines,
by consolidating some of the output into the relevant banner line.
To solve 3., indent the status output to the same level as the
'status:' text in the banner.
> compare: output improvements

- tests/conftest.py
- tests/test_config.py
- tests/test_project.py
> test_compare: add config_tmpdir fixture to block ignore-branches 

- src/west/version.py
> version: 1.2.0a1

- src/west/app/project.py
- tests/test_project.py
Add fixes and features added to main during alpha testing of v1.3.
Cherry-picked commits from `main`
> Backport main to v1.3 branch

- pyproject.toml
Set the pyproject version to 1.3.0a3.
> version: 1.3.0a3

- src/west/app/project.py
NTFS: the gift that keeps on giving...
See October 2024 discussion in #558
> Add some NTFS checks

- pyproject.toml
Set the pyproject version to 1.3.0.
> version: 1.3

- src/west/app/project.py
- tests/test_project.py
> app: list: additional support for inactive projects

- pyproject.toml
Update the pyproject version to 1.4.0 alpha 1.
> version: 1.4.0a1

- .github/workflows/test.yml
- .gitignore
- tox.ini
Upload test reports to Codecov to track pytest results.
Test dashboard: https://app.codecov.io/gh/zephyrproject-rtos/west/tests
> Codecov test result reporting
