west/runner/core.py

A couple of docstrings are causing issues when imported into Sphinx as they are not in ReST format; fix these up.
CC: @ulfalizer
CC: @tejlmand

Trivial fix for docstrings for ReST integration

---

.gitignore
README.rst
bootstrap/__init__.py
bootstrap/main.py
setup.py
west/main.py

This pull request adds a bootstrap script, and makes that what would get uploaded to PyPI.
Not done:
1. allow reinitializing an already initialized directory (to get another manifest, manifest branch, or reinitialize the west repository)
2. macOS, Windows testing
3. actually push to PyPI (I tested this using `pip install -e` as described in the README)
4. auto-updating west itself
I think that 1. and 2. should block 3., but that 4. ought to be done within west itself, since it's more complicated. Once 1. is done and we're happy with the cross platform support I'm hoping (fingers crossed here!) that we won't have to touch the bootstrap script hardly ever.
One (I think) nice behavior of this script is that it works like "git init" rather than "repo init" in that you can optionally specify …

Support for bootstrapping west

---

.gitignore
.shippable.yml
tests_requirements.txt

This ought to provide shippable integration for the recently merged test suite. It's my first time though, so I expect it might have some issues (and I haven't set up an account on shippable itself, just tried to do the local integration here).

Shippable integration

---

requirements.txt
src/west/cmd/project.py
src/west/cmd/schema.yml
src/west/main.py
src/west/util.py
tests/west/project/__init__.py
tests/west/project/manifest.yml
tests/west/project/test_project.py

Add simple Google repo-like functionality, for dealing with multiple Git
repositories.
The command set is mirrored after Git. All commands except
'list-projects' accept an optional list of projects, and default to all
(cloned) projects.
- west list-projects
Lists projects and their repositories
- west fetch
Clone/fetch projects. Supports 'clone-depth', for making shallow
clones.
- west rebase
Rebase local branches to the revision specified in the manifest
- west pull
'west fetch' + 'west rebase' (similar to 'sync' in Google repo)
- west branch
Create a new branch in one or more repositories (for working on some
issue)
- west checkout
Check out a branch in each repository that has it
- west diff
Run 'git diff' in each repository
- west status
Run 'git status' in reach repository
There's no …

Add project commands for dealing with multiple repositories

---

src/bootstrap/main.py

The bootstrap script no longer works properly since the src/ directory was added to support test cases. Fix that.

bootstrap: fix path after test reorg

---

src/west/cmd/project.py
src/west/main.py
tests/west/project/test_project.py

Passes its command as-is to the shell, within the repositories of each
of the specified projects (or all cloned projects by default).
I was thinking of making the shell quoting for long commands optional,
by joining all the words with a space or the like, but it might get
tricky with argparse. Could look into it more later.
Piggyback some cleanup: Make the absolute path of a project available in
project.abspath, to avoid having to do a bunch of join()s with
util.west_topdir().
Fix some copy-paste comment mess-ups in the tests too.

Add 'forall' command

---

src/west/cmd/project.py
tests/west/project/test_project.py

Analogous to running 'git branch', except for all projects. Also lists
the project(s) each branch appears in.
Example output:
$ python3 -m west branch
FIX-FOO            zephyr, Kconfiglib
manifest-rev       zephyr, net-tools, Kconfiglib
master             zephyr, net-tools
zephyr             Kconfiglib
I'm planning to change 'git clone' into 'git init' + 'git remote add' +
'git fetch' later, which avoids creating the last two local branches.
Maybe manifest-rev should be hidden as well.

Make 'west branch' by itself list all local branches

---

src/west/cmd/debug.py
src/west/main.py
src/west/runner/core.py
src/west/runner/jlink.py
src/west/runner/pyocd.py

Introduces a new west command to start a debugging session without
programming the flash. This can be used when you want to debug a Zephyr
application that is already running.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

runner: Introduce attach command

---

src/west/cmd/project.py

Hi @ulfalizer, I gave the new project commands a go and (with these patches) was able to get a manifest written for my company's Zephyr-based product and run 'west init + west fetch' successfully.
The only real fix is the _verify_repo()-related patch; everything else is just future-proofing, OCD, and the like.
Haven't tested anything else yet but optimistic about the start! Thanks for all the great work.

Misc fixes

---

requirements.txt
src/west/cmd/project.py
src/west/log.py
src/west/main.py

Commit messages say it all:
```
cmd: project: Use 'git init' + 'git fetch' instead of 'git clone'
Use this command sequence instead of 'git clone':
git init <path>
In <path>:
git remote add origin <url>
git [--depth n] fetch origin [<branch-or-SHA>, if clone-depth is used]
git update-ref refs/heads/manifest-rev <branch-or-SHA>
git checkout --detach refs/heads/manifest-rev
This has two advantages:
- No local branches are created automatically, giving us better
control over the initial state of the repository
- The final three commands can be reused for fetching changes from an
existing repository, giving a single code path for all fetches
Let the initial state of a repository be a detached HEAD at
'manifest-rev'. We could also have the initial state have nothing at all
checked out, but it …
```

Use 'git init' + 'git fetch' instead of 'git clone', + a small cleanup and colorized output

---

src/bootstrap/main.py
src/west/cmd/project.py
src/west/util.py
tests/west/project/test_project.py

I was confused by the other design, because I intuitively expected West
metadata to go in .west/. To me the other design feels a little bit like
having an empty /home/foo/user/ directory that marks the /home/foo/
directory as containing the user's files.
Use west/ instead of .west/ to avoid "hiding" the implementation of the
building/flashing commands. I would've preferred to split them from the
repo-like functionality instead, but if they're going to be in the same
repository, then it's a decent comprise.
Remove the code that hides the west directory on Windows (via 'attrib')
as well, since it doesn't make much sense anymore.
This commit also fixes a small bug in west_topdir(): A west/ in the root
directory wasn't found.

Store West source code and the manifest in west/

---

README.rst
setup.py
src/bootstrap/main.py
src/west/util.py
tests/west/project/manifest.yml
tests/west/project/test_project.py

This adjusts the way the top level west directory is found by searching for a `west/.west_topdir`  file.
I've piggybacked some trivial fixes, as well as refactorings to the project test suite.

Tweak west topdir

---

src/west/_bootstrap/main.py
src/west/main.py

In order to simplify debugging and support to users starting with west,
print the location of both the bootstrapper and west itself when running
west --version.

version: Print script location next to version

---

src/west/runners/pyocd.py
tests/west/runners/test_pyocd.py

Add support for specifying the SWDCLK frequency in Hz for pyOCD.
Signed-off-by: Henrik Brix Andersen <henrik@brixandersen.dk>

runner: pyocd: add support for specifying SWDCLK frequency

---

src/west/runners/pyocd.py
tests/west/runners/test_pyocd.py

This doesn't affect the default functionality of the runner, but it's nicer to flash hex files if possible. For example, some tools find it easier to post-process hex files than binary files for flashing on the board.
Keep test cases up to date.

runners: pyocd: prefer hex files to bin files if possible

---

src/west/_bootstrap/version.py

This mirrors what gets done in Zephyr.

Set bootstrap version to post-release 0.2.99

---

src/west/commands/project.py

The URL is taken literally from the manifest. It's unlikely that anyone
would put a URL starting with a '-', but having weirdly named stuff be
correctly interpreted by Git could help with diagnosing bugs.
Maybe some other Git commands could be tightened up too, but they looked
safe from a glance.

commands: projects: Put '--' before URL in 'git remote add'

---

src/west/commands/project.py
src/west/main.py
tests/west/project/test_project.py

I got tired of typing 'list-projects' all the time.
'list' might be a bit less obviously related to projects, but I don't
think it would be that bad. Feel free to complain.

Rename 'list-projects' to 'list'

---

src/west/_bootstrap/main.py
src/west/commands/project.py
src/west/config.py
src/west/log.py
src/west/main.py

```
Get west and manifest revisions from a configuration file
Add configuration file support via the standard Python configparser
module, which uses a Git-like .ini format. Use it to save the west and
manifest revisions specified when running 'west init', and use the saved
revisions when updating the west and manifest repositories.
Configuration file paths are based on Git, for consistency with the
Git-like commands. See the FILES section in git-config(1). Mac OS and
Windows paths were checked by Carles Cufi with
'git config --list --show-origin'.
Add some new shorthands to _expand_shorthands() in project.py to factor
out some logic while removing the hardcoding of the west and manifest
upstream branches. The qual-* versions of shorthands give the full path
to refs (refs/heads/foo, …
```

Get west and manifest revisions from a configuration file + support any revision format + misc.

---

src/west/commands/project.py

This came up in #52.
I'm not sure what the appropriate field widths are ({:n}). We could
tweak it later if some fields turn out to be too short/long.
Fixes: #37

commands: project: Show remote URLs for projects in 'west list'

---

src/west/commands/project.py

As long as that's the case, it should be documented.
I suspect it might be a feature. If you've created a branch do to some
work with 'west branch fix-stuff repo1 repo2 repo3', then it's probably
unexpected if 'west checkout fix-stuff' checks out a remote branch
'fix-stuff' that happens to exist in some other repository.
Fixes: #34

commands: project: Clarify that 'west checkout' deals with local branches

---

README.rst
src/west/_bootstrap/main.py

Using `-u` as the manifest URL is confusing because:
* We use `-w` for the west url
* We use `--wr` for the west revision
* We use `--mr` for the manifest revision
Instead, use `-m` which is consistent with the rest of the options.

bootstrap: Rename -u to -m for consistency

---

src/west/_bootstrap/main.py

Add 'git@' to the list of accepted prefixes. Alternatively, any username
could be accepted, but keep it simple while we have the URL check.
IMO, the check should be removed instead. It artificially restricts us to
a subset of what Git really supports, for no good reason.
Also fix a typo: s/git-shh:/git-ssh:/

bootstrap: Don't error out for 'git@' URLs

---

src/west/commands/project.py

'git fetch/pull' by default doesn't fetch tags from remotes specified as
URLs, which is what we use. Pass --tags to get them.
This will only fetch tags pointing to commits reachable from the
manifest revision being fetched.
Fixes: #92

commands: project: Fetch tags from remotes

---

src/west/runners/pyocd.py
tests/west/runners/test_pyocd.py

The mimxrt1052 does not have any internal flash, therefore a reset after
load blows away the code when loaded into sram. Reverse the order of the
pyocd commands such that the load follows the reset.
The command order now matches jlink.
Signed-off-by: Maureen Helm <maureen.helm@nxp.com>

runners: pyocd: Don't reset after load

---

src/west/commands/project.py
src/west/manifest-schema.yml
src/west/manifest.py
tests/west/manifest/invalid_reserved_name_manifest.yml
tests/west/manifest/invalid_reserved_name_west.yml

Add two options to `west list` will be useful when processing its output in programs:
- `-p` / `--path`: just print project paths
- `-a` / `--abspath`: just print project absolute paths (takes precedence)
Also add a `-s` / `--special` option to include the "special" projects (west and the manifest) in the output.
The command `west list -as west` will be needed by the Zephyr documentation system to find the West source code for use in autodoc Sphinx directives.
The command `west list -a` will be needed by the Zephyr build system to obtain the paths of all West projects to consider for building.

List enhancements

---

src/west/_bootstrap/version.py

After releasing 0.3.0, set the .99 marker.

version: Set post-release version to 0.3.99

---

scripts/west-completion.bash
src/west/commands/run_common.py
src/west/runners/arc.py
src/west/runners/bossac.py
src/west/runners/core.py
src/west/runners/dfu.py
src/west/runners/esp32.py
src/west/runners/intel_s1000.py
src/west/runners/jlink.py
src/west/runners/nios2.py
src/west/runners/nrfjprog.py
src/west/runners/nsim.py
src/west/runners/openocd.py
src/west/runners/pyocd.py
src/west/runners/xtensa.py

Rename variables to make west more agnostic, and therefore potentially
more flexible, to what it is flashing.
This is a small step towards solving #7868 and other similair issues
in Zephyr. Essentially, sometimes, for instance when a bootloader is
used, or a dual-core platform is used, we need to flash multiple
images/application's, not just the 'kernel'.
To prepare 'west' for this future feature we make it agnostic to what
kind of hex/bin file it is flashing by taking the 'kernel' name out of
the variables. This allows the hex file to contain not just the
kernel, but also a bootloader, or a second image.
NB: Untested, would like to agree on the naming of the elf before testing.

cmake: west: Take the 'kernel' name out of the .bin/.hex file

---

src/west/commands/project.py
src/west/manifest.py
tests/west/manifest/test_manifest.py

Make commands that accept project names also accept project paths. For
example, 'west branch fix-foo .' can be run inside the zephyr/
directory, instead of running 'west branch fix-foo zephyr'.
Paths are mapped to projects by checking if the realpath (canonicalized
absolute) of any project is a prefix of the realpath of the supplied
path. That method will map subdirectories of projects to the project as
well.
Switch to using realpath() to calculate project.abspath as well, which
streamlines things and gets rid of gotchas related to symbolic links.
Project names and paths can be mixed in the same command. If both a
project name and a path matches, the name takes precedence (this can
always be worked around with './foo').

commands: project: Allow projects to be specified via their path

---

src/west/commands/run_common.py

Check for multiple versions of names to be compatible with more
versions of Zephyr.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

commands: Be compatible with more Zephyr versions

---

src/west/commands/flash.py
src/west/runners/jlink.py

@pfalcon does this fix your issue?
As explained in the log, it is certainly our intent that `west -v flash` prints enough information for users to stop using the wrapper if they desire.

runners: jlink: debug log commander script contents

---

src/west/_bootstrap/main.py
src/west/main.py

The error output when the bootstrapper is called without arguments or with -h is lacking. Try to improve it.
Tweak the output when called without arguments when an installation is found as well, in the same spirit.
Fixes: #108

Be more helpful to newcomers.

---

src/west/commands/project.py

Older versions of git lack support for --rebase=false
Thus splitting pull into a fetch and merge is safer, as well as it
provides better help on which steps are failing.
See the discussion from IRC.
```
#zephyr-meta
[2018-11-21 09:36:32] <tejlmand> ok, downloading 2.1.0 from Aug 2014.
[2018-11-21 09:36:55] <tejlmand> once you have a patch, I can verify behavior
[2018-11-21 09:37:18] <tejlmand> we should be pretty safe, if everything is working with 2.1.0
[2018-11-21 09:45:17] <tejlmand> with 2.1.0 I get
[2018-11-21 09:45:25] <tejlmand> https://www.irccloud.com/pastebin/735rrjAE/
error: unknown option `rebase=false'
usage: git fetch [<options>] [<repository> [<refspec>...]]
or: git fetch [<options>] <group>
or: git fetch --multiple [<options>] [(<repository> | <group>)...]
or: git fetch …
```

git: split pull into fetch+merge

---

README.rst
src/west/_bootstrap/main.py
src/west/_bootstrap/west-schema.yml
src/west/commands/project.py
src/west/manifest-schema.yml
src/west/manifest.py
tests/west/manifest/invalid_bad_default_remote.yml
tests/west/manifest/invalid_duplicate_project_path.yml
tests/west/manifest/invalid_ill_defined_project.yml
tests/west/manifest/invalid_no_projects.yml
tests/west/manifest/invalid_reserved_name_manifest.yml
tests/west/manifest/invalid_reserved_name_west.yml
tests/west/manifest/invalid_too_flat.yml
tests/west/manifest/invalid_west_section.yml
tests/west/manifest/test_manifest.py
tests/west/project/test_project.py

~Early RFC to get feedback, only partially tested~
Full implementation with additional proposal by @tejlmand:
https://github.com/carlescufi/west/pull/1
Also coupled to this PR to the manifest:
https://github.com/zephyrproject-rtos/manifest/pull/6
Fixes #106 (we will be able to simply tag the manifest with this PR)

Read west URL and revision from  manifest instead of config file

---

src/west/_bootstrap/main.py
src/west/_bootstrap/version.py
src/west/main.py

This PR fixes a bug in the bootstrapper which caused 'west debug' to stop working properly.
We'll need to make a similar change to zephyr/scripts/west while we maintain that:
https://github.com/zephyrproject-rtos/zephyr/blob/master/scripts/west#L84
Because this is a bootstrapper change, we need to cut a new west release to make this available to users.
If this gets merged, I'll push a tag and update PyPI as well.

Fix gdb ctrl-c regression

---

src/west/commands/project.py

Fixes: #139
Fixes the issue of fetching SHAs when specified in manifest file.
It is checked if a revision is a SHA, in which case the fetch is
performed on the url and afterwards the manifest-rev reference is
updated to the SHA.

project: Fixed issue with fetching revision SHA

---

src/west/runners/jlink.py

On Microsoft Windows, the default name of the JLink executable is
"JLink.exe", while on *NIX it is instead "JLinkExe". Detect and
correctly set the default name based on the platform.

runners: jlink: Default to correct JLink executable

---

src/west/main.py

We need to do another copy of west into Zephyr to get some runner fixes and features, but some assumptions have crept back into the code that we're in a multirepo install.
Fix these so we can use flash and debug commands in a monorepo Zephyr installation.

main.py: fix monorepo use cases

---

src/west/config.py

Trivial cleanup based on git blame.

config.py: add missing copyright and license

---

src/west/_bootstrap/main.py
src/west/commands/project.py
src/west/config.py
src/west/main.py
src/west/manifest-schema.yml
src/west/manifest.py
src/west/util.py
tests/west/manifest/invalid_reserved_name_manifest.yml
tests/west/manifest/test_manifest.py
tests/west/project/test_project.py

This PR includes the following:
- Ability to have manifest file inside a project repository
- `self` tag introduced in manifest
- Renaming of `default.yml` to `manifest.yml`
- Folder `west` renamed to `.west`
- `west init` is now continued inside `west` repository after bootstrapper has cloned manifest repository
A branch of Zephyr with `manifest.yml` is available for testing:
https://github.com/tejlmand/zephyr/tree/manifest-branch
To test:
`west init -m https://github.com/tejlmand/zephyr --mr manifest-branch`

Manifest in project repository

---

src/west/_bootstrap/main.py

A git clone of manifest repository into temporary folder on windows
will contain read-only files.
This will cause shutil.rmtree to fail and abort bootstrapping.
Current fix is to ignore such errors on windows and rely on windows
temp folder cleanup.

bootstrapper: Ignore errors on temp folder cleanup

---

src/west/_bootstrap/main.py
src/west/commands/__init__.py
src/west/commands/build.py
src/west/commands/command.py
src/west/commands/debug.py
src/west/commands/flash.py
src/west/commands/project.py
src/west/commands/run_common.py
src/west/commands/west-commands-schema.yml
src/west/main.py
src/west/manifest-schema.yml
src/west/manifest.py
src/west/util.py
tests/west/manifest/invalid_west_commands_1.yml
tests/west/manifest/invalid_west_commands_2.yml
tests/west/manifest/invalid_west_commands_3.yml
tests/west/manifest/test_manifest.py

Add support for discovering and executing out-of-tree commands. I've also added some follow-on patches to the major changes just merged allowing arbitrary projects to contain the manifest.
I need to finish writing test cases, which no doubt means there are still a few silly bugs in addition to the one minor issue I'm aware of [1], but this passes all our existing tests plus a couple of sanity checks on my machine.
I've also verified some basic operation with the following external tests module. (Put it in manifest/test.py to test at home.)
```
from west.commands import WestCommand
TEST1_HELP = 'test one help'
TEST1_DESC = 'test one description'
TEST2_HELP = 'test two help'
TEST2_DESC = 'test two description'
class test1(WestCommand):
def __init__(self):
super(test1, self).__init__( …
```

Extension commands

---

src/west/commands/command.py
tests/west/project/test_project.py

This pr rebases nicely onto PR/156
Added tests to ensure missing extension files (in case a project in
not cloned) will not cause west built-in commands to fail.

extension_commands: Added test and allow for projects not cloned

---

src/west/commands/command.py
src/west/commands/west-commands-schema.yml
src/west/main.py
tests/west/project/test_project.py

For various reasons, we don't load extension command modules until the
user has requested that we run a particular extension command.
As is, this limits the "west -h" output to the extension command names
and the projects which define them, which isn't as nice as what
built-in commands get.
Allow extension commands to provide help text by extending the schema
for each command entry with an optional "help" key, and display it in
the output. If it is missing, a default is provided which recommends
just running "west $EXTENSION_COMMAND_NAME -h".
Fix the help formatting by adding a colon after each extension command
name to match the style used for built-ins while we are here.

commands: allow extension commands to provide help strings

---

src/west/_bootstrap/main.py

The current west bootstrapping does not support:
```
west init --mr pull/<pr>/head
```
as example:
```
west init --mr pull/12666/head
```
fails with error:
```
fatal: Remote branch pull/12666/head not found in upstream origin
Traceback (most recent call last):
```
this PR allows to do `west init` on a pr.
Changing `west init` into using
- git init
- git fetch
- git checkout
as this allows users to specify other refs, such as pull/<no>/head
which is not possible with git clone on github.

bootstrap: allow bootstrapping a manifest repository using ref to a pr

---

README.rst

URL to west doc points to non-existent page (missing tools/ in URL).

README.rst: correct URL to west documentation

---

src/west/_bootstrap/main.py

We're seeing warnings when people have ZEPHYR_BASE set to the `<directory>` they pass to `west init -l <directory>`.
Avoid them exactly in the situation that `<directory>` is a zephyr repository by using the manifest directory as ZEPHYR_BASE. For upstream, that is correct anyway.
Merge a couple of lines while here as a cosmetic improvement.
Fixes: #167

bootstrapper: improve heuristic for --zephyr-base

---

src/west/commands/__init__.py
src/west/commands/command.py
src/west/commands/project.py
src/west/main.py
tests/west/project/test_project.py

This series is mostly fixes.
The last patch contains a couple of new options for `west update`:
- `--keep-descendants` (or `-k`): if a project has a local branch checked out that is a descendant of the new `manifest-rev`, don't leave my branch behind
- `--rebase` (or `-r`): if a project has a local branch checked out, rebase it onto the new `manifest-rev`
This is a first step towards generalizing this command to support common use cases.
I can split the fixes up into their own PR, but I'm hoping that these options -- since they are opt in and apply only to projects, not the manifest repository -- will be uncontroversial.

Misc fixes and `west update` with `--keep-descendants` and `--rebase`

---

src/west/main.py

Fixes: #173
This commit adds sys.argv[0] when restarting west after an update.

selfupdate: Fix for west selfupdate mechanism

---

src/west/commands/__init__.py
src/west/commands/command.py
src/west/main.py

A couple of trivial fixes:
- fix the error handling when we get a BadExternalCommand exception
- remove a stupid and unnecessary restriction on the names of extension commands

Extension command fixes

---

src/west/log.py

Red is too aggressive for warnings, switch to yellow instead.

log: Use yellow for warnings

---

src/west/main.py

On Windows, sys.argv[0] is the path to an executable (.exe)
instead of a Python script. Execute that file directly instead
of relying on Python to do so.

main: Execute sys.argv[0] on Windows

---

src/west/_bootstrap/main.py
src/west/_bootstrap/version.py

Cut a point release to incorporate bootstrapper fixes. We need this to get the fix for #175 into the hands of users.

West v0.5.2.

---

src/west/_bootstrap/main.py

Fixes: #186
Instead of cloning manifest repo into temp directory, which can be a
disk different from final destination, then the manifest repo is now
cloned into .west, and from there, moved to its final location.

init: Change west init to clone manifest repo inside .west

---

src/west/commands/project.py

This fixes an issue where west update could fail to checkout a SHA as
revision if that SHA was located on a branch that was not being
fetched.
This should address the issue discover by @nashif 
> playing with adding a new repo into west.yml
```
From https://github.com/zephyrproject-rtos/tinycbor
* branch            HEAD       -> FETCH_HEAD
fatal: update_ref failed for ref 'refs/heads/manifest-rev': cannot update ref 'refs/heads/manifest-rev': trying to write ref f
FATAL ERROR: Command 'git update-ref refs/heads/manifest-rev 3ef9fedf6d4872a374a0d58f6d207ccbfee670ff' failed for tinycbor (t)
```
> I just added:
```projects:
- name: net-tools
revision: 30b7efa827b04d2e47840716b0372737fe7d6c92
- name: tinycbor
revision: 3ef9fedf6d4872a374a0d58f6d207ccbfee670ff```

fetch: With revision as a SHA west will fetch default ref-space

---

src/west/commands/project.py
src/west/manifest.py

west list --format={abspath} is intended to use with Zephyr's CMake
build system. In order for CMake not escape path, such as `C:\<path>`
PurePath.as_posix() is used to ensure forward slashes when printing
abspath.

list: updated abspath to use PurePath.as_posix()

---

src/west/commands/project.py
tests/west/project/test_project.py

PR #189 with additional commit that makes `west selfupdate` behave similar to `west update` but for the `west repo`

Manifest command selfupdate

---

src/west/_bootstrap/version.py

I screwed up the 0.5.3 upload to PyPI. Then I tried to delete it and
re-upload. This turns out to be impossible -- file names can't be
reused even if the package has been deleted.
So 0.5.3 is the point release that never was, unfortunately. 0.5.4
will be the same, but with a different number. Fun times / whoops.

West v0.5.4

---

src/west/manifest.py
tests/west/project/test_project.py

Since the python object is named url_base, this field is getting
frozen via as_dict with an underscore rather than the dash required
by the schema.
Signed-off-by: Andy Doan <andy@foundries.io>

manifest: Serialize remote[url-base] properly

---

tox.ini

sys.platform returns "darwin" on macOS. Fix the .ini file so that tests
actually run on macOS.

tox: Fix .ini file on macOS

---

src/west/main.py

Delete some # characters left over from an improperly reflowed paragraph.

main.py: trivial comment fix

---

scripts/west-completion.bash
src/west/commands/project.py

Since excluding west from an update procedure is limited to a single
command now (west update), clarify that in the code and use a more
explicit flag name.

project: Rename --no-update to --exclude-west

---

src/west/_bootstrap/main.py

Fixes: #212
If ZEPHYR_BASE was set in environment, `west init` fails.
This commit ensures `west init` can still run, as long as it is
invoked outside of a west managed project tree.

init: Init will allow cloning a project when ZEPHYR_BASE is set.

---

src/west/_bootstrap/main.py

On Windows 10, with Python 3.7.1, the following was not working:
west init -l zephyr/
or
west init -l zephyr\
because of the trailing (back)slash being interpreted as an additional
folder and west initializing itself inside the zephyr folder instead of
doing it in the enclosing one.
By normalizing the path we avoid this issue entirely.
Note that this is actually due to a regression that was fixed:
https://bugs.python.org/issue31047

bootstrap: Use normpath() to avoid initializing in wrong folder

---

src/west/main.py

Remove trailing whitespace from the format_help() return value. This prevents an extra blank line from appearing in the west --help output.

main.py: fix extra newline in west --help

---

src/west/main.py

This commit ensures that zephyr.base will be joined with west_topdir()
when a relative path is used in west config.
The previous solution was using os.path.abspath which would give
different results depending on current location when invoking west
command.
The advantage of allowing relative path in .west/config over requiring
an absolute path, is that it allows a user to rename a project's parent
folders without having to update zephyr.base.
Fixes #231 

zephyr base: fixed west config zephyr.base when relative

---

src/west/_bootstrap/version.py
src/west/commands/project.py
tests/west/commands/conftest.py
tests/west/commands/test_project.py

It has been discovered that in the event that a different remote is
added to manifest file which contains same branches but cannot be
fast forwarded into the local refs space, then a west update will fail
with the error:
! [rejected] <branch> -> refs/west/<branch> (non-fast-forward)
This commit fixes this issue by introducing '-f' when fetching.
This commit has additional test for verifying the fix.
Fixes: #236 

git: git fetch now uses -f

---

src/west/_bootstrap/main.py
src/west/_bootstrap/version.py

Two bootstrapper fixes:
- check for git with shutil and print a sensible message if it's not found and is needed
- print a better error message if west.main can't be imported

West v0.5.8

---

src/west/commands/project.py

format() throws IndexError on some invalid format strings. Handle that
rather than dumping stack.

commands: trivial west list error handling fix

---

src/west/commands/command.py
src/west/commands/config.py
src/west/configuration.py
src/west/log.py
src/west/main.py
src/west/util.py
tests/conftest.py
tests/test_config.py

The goal of this pull request is to add all the features I would like `west config` to have for 1.0.
(I'm not 100% happy with the user friendliness of the `west.configuration` API, though, so I might want to send a follow-up with some deprecations and cleanups.)
The configuration API currently only allows getting and setting individual config options. The test cases are a great starting point for validating this, but they work only at the command level and do not test the underlying APIs, or that the command-line interface and module APIs work together as expected.
To flesh out the interface for both, this:
- adds `west config --list` to print all options and their values
- adds `west config -d [--global | --system | --local] foo.bar` to delete `foo.bar` from an individual file, or the …

Flesh out west config command and west.configuration API

---

.shippable.yml
src/west/commands/project.py
src/west/manifest.py
tests/test_project.py

- The default west list format string is not particularly readable
most of the time. Tweak it so it's better.
- replace multi-word strings like "(not set)" with single word
equivalents like "N/A", which are easier to deal with in pipelines
to cut, awk, etc.
- add a new {sha} format specifier that always produces a 40-character
SHA, or the string N/A padded to the correct length.

Incompatible list improvements

---

src/west/commands/project.py

Invoking 'west update' without the '-r' (rebase) option typically causes
messages like this to be issued:
WARNING: left behind ci-tools branch "mybranch"; to fast forward back,
use: git -C ../tools/ci-tools checkout mybranch
This is actually two messages somewhat confusingly compressed into one:
1. How to switch back to "mybranch",
2. "mybranch" is head of manifest-rev and doesn't need to be rebased.
Some issues:
- While 2. is secondary, it fills most of the space and draws most of the
attention.
- Whenever plain git uses "fast forward" there doesn't seem to ever be
any branch switching involved. Yet switching branch is the main
message here.
- The unfortunate "forward back" sequence sounds weird when parsed too
quickly.
As discussed and agreed with Marti on Slack, isolate and "downgrade" …

project: rephrase message "branch left behind, to fast forward... "

---

src/west/manifest-schema.yml
src/west/manifest.py
src/west/version.py
tests/manifests/invalid_repo_path_and_url.yml
tests/test_manifest.py

Compared to rc1, this adds a bugfix and a new feature, the project 'repo-path' attribute, to allow continuing use of remotes with non-unique project names.
Fixes: #283

West 0.6.0 rc2

---

src/west/commands/__init__.py
src/west/commands/project.py
src/west/log.py
src/west/main.py
src/west/manifest.py
tests/test_project.py

This is a bunch of cleanup and prep work patches I think should be sent on their own (since they're already quite a lot of commits).
It's a basis for two lines of development going on in semi-parallel:
- add a smarter project fetching strategy that avoids fetching projects when the revisions are definitely already available locally
- some downstream-specific extension commands that want to use some of the code that's currently hidden in private project.py methods
I should add:
Fixes: #242 
By removing the unsupported behavior from the test cases and help strings.

Prep work improvements

---

src/west/manifest.py
tests/test_manifest.py

The control flow when there is an unknown project is wrong: this is
calling is_cloned() on None. Indent it properly and add a regression
test.
Signed-off-by: Marti Bolivar <marti.bolivar@nordicsemi.no>

manifest: fix get_projects() for unknown projects

---

src/west/commands/config.py

When requesting config values with the wrong key format (not section.key), west config crashes on producing the error message. Removes the non existent kwarg 'exit_code' and adds the missing format statement.

commands: config: fix error message when providing wrong key formating.

---

src/west/version.py

Compared to v0.6.0, the user-visible features in this point release are:
- an optimized west update via its new --fetch command line flag and
update.fetch config option. The default value, "smart", skips fetching
SHAs and tags which are available locally.
- better and more consistent error-handling in the manifest, diff, status,
forall, and update commands.
- the west list command now accepts uncloned projects unless its
format string requires data that must be obtained from the project
repository.
- multi-repo commands now accept partial SHAs in more cases. For
example, "west init --mr SHA_PREFIX" works now.
The developer-visible additions to the west APIs are:
- west.log.banner(): new
- west.log.small_banner(): new
- west.manifest.Manifest.get_projects(): new
- …

West version 0.6.1

---

src/west/commands/project.py
src/west/version.py

Fix a critical west update issue in a new v0.6 branch. I'm cutting a branch because master's west APIs have diverged to the point that I think the next west should be v0.7, and we're not ready to cut a release yet on those changes.
Fixes #298

Fix west update in new v0.6 branch

---

setup.py

This allows uploading vX.Y.Z.devN development snapshots to PyPI as
needed, without having to touch version.py or go through the pull
request process.
Signed-off-by: Marti Bolivar <marti.bolivar@nordicsemi.no>

setup.py: allow environment override of the version

---

src/west/commands/__init__.py
src/west/commands/project.py
src/west/main.py
tests/test_project.py

This new command will just print the root or top level directory of the west installation (or an error if none is found). We also tweak some of the help text while we're here to keep 'west help' nice and clean.
cc: @marc-hb @bjda
Discussion in https://github.com/zephyrproject-rtos/west/issues/310 brought up a request for a way to print the installation top level directory. We've been discussing whether or not to add this for quite some time now. It's clearly useful to some users, so let's just add it.

add 'west topdir' command

---

src/west/main.py

Every time ZEPHYR_BASE and west config clashed with each other it's been
because I moved across _several_ west installations and forgot to
adjust ZEPHYR_BASE. Fix the warning message so:
- it doesn't refer to the "west config" like there's only one!
- it shows which exact west topdir it got a west config from;
- it shows the actual value in west config and not a construction.
Before:
```
WARNING: ZEPHYR_BASE=/home/john/west1/zephyr in the calling
environment will be used, but was set to
/home/john/west2/zephyr in west config.
```
After:
```
WARNING: ZEPHYR_BASE=/home/john/west1/zephyr in the calling
environment will be used, but was set to
"zephyr" subdirectory in [west config of] /home/john/west2
```
When something goes wrong, the user unfortunately needs the "raw" /
low-level data; …

main.py: clarify warning when ZEPHYR_BASE != west config

---

src/west/main.py

We're getting increasing interest in west being its own tool, to be
used standalone from Zephyr. Unfortunately we are still too tightly
coupled for that to be possible, but the current behavior of erroring
out is not correct. Let's downgrade that to a warning and have the
warning print the current workaround.
Relates to: #246
Signed-off-by: Marti Bolivar <marti.bolivar@nordicsemi.no>

main: downgrade "no zephyr" to wrn(), add workaround

---

src/west/manifest.py

cc: @skelliam
In certain situations, such as if the project remote is an empty
repository or otherwise prevents 'west update' from setting up the
manifest-rev branch, we can't freeze the manifest even though a
project has been cloned.
Handle that by raising RuntimeError, so that higher layers know what
went wrong and can print a sensible error message instead of dumping
stack.
Fixes: #314
Signed-off-by: Marti Bolivar <marti.bolivar@nordicsemi.no>

manifest: improve Manifest.as_frozen_dict robustness

---

src/west/manifest-schema.yml
src/west/manifest.py
src/west/version.py
tests/test_manifest.py

A new attempt. GitHub won't let me reopen the previous pull request https://github.com/zephyrproject-rtos/west/pull/321, sorry.
Fixes: #126 
There are 3 different error paths on incompatible versions:
- help path: warn that extension command help will be missing and most commands won't run is printed
- error path: commands which are known to require the manifest (update, list, ...) print a fatal error with similar info for the help path
- watch-out path: commands which don't need the manifest (config, topdir) print a warning that they ought to work, but an upgrade is needed
Examples:
```
$ west [help,--help,-h]
WARNING: west v0.7 or later is required by the manifest
West version: v0.6.99
Manifest file: /home/mbolivar/zp/zephyr/west.yml
Cannot get extension command help, and most commands …
```

Manifest version check

---

src/west/main.py

This prevents us from dumping stack on a broken pipe.
Depending on when the exception occurs, we may still see something
like this:
Exception ignored in: <colorama.ansitowin32.StreamWrapper object at 0x7fc755d5c990>
BrokenPipeError: [Errno 32] Broken pipe
We can try to avoid even this in Python 3.8, which added a
sys.unraisablehook() that can be called instead. Let's defer that for
now, though; 3.8 hasn't hit my Arch installation yet and I want to
wait for that to start playing with it.

main: basic BrokenPipeError handling

---

.shippable.yml
setup.py
src/west/commands/__init__.py
src/west/commands/project.py
src/west/main.py
src/west/manifest-schema.yml
src/west/manifest.py
tests/test_manifest.py

This is incomplete, because support for `import` keys with map values is not supported. However, you can use import keys which are:
- booleans
- files
- directories
- sequences of files and directories
Basic test cases at the west.manifest API level are supported, but I want to write much more detailed test cases before we release a version of west with these features.
However, I think this is ready for review and initial merge to get the feature into the hands of users and start collecting real feedback.

Initial support for manifest imports

---

src/west/commands/project.py
src/west/manifest.py

As discussed in PR #331 the cleanup of `refs/west` has been split into separate PR.
Note: Cleanup is done BEFORE updating the `manifest-rev` as this ensures the update is the newest entry in reflog, as example:
```
fec2a3c (HEAD, ncs/master, manifest-rev) manifest-rev@{0}: west update: moving to fec2a3c3b4d79b7eb6d1ebdf24e6813476116769
9da9943 (tag: v1.1.0, ncs/v1.1-branch) manifest-rev@{1}: west fetch: entry for refs/west/v1.1-branch
efcbc25 (tag: v1.0.0, ncs/v1.0-branch) manifest-rev@{2}: west fetch: entry for refs/west/v1.0-branch
....
```

git: clean west ref space after fetching

---

src/west/commands/__init__.py
src/west/commands/config.py
src/west/commands/project.py
src/west/configuration.py
src/west/main.py
src/west/manifest.py
src/west/util.py
tests/conftest.py
tests/test_manifest.py
tests/test_project.py

DNM, depends on: https://github.com/zephyrproject-rtos/west/pull/351
This adds a commit `tree-wide: rename "installation" to "workspace" `, which reflects some discussions we've had around doing just that.
cc: @marc-hb

housekeeping: workspace, not installation

---

.shippable.yml
setup.py
src/west/__init__.py
src/west/version.py
tests/conftest.py
tests/test_help.py
tests/test_manifest.py
tests/test_project.py
tox.ini

DNM, depends on these two:
- https://github.com/zephyrproject-rtos/west/pull/351
- https://github.com/zephyrproject-rtos/west/pull/352
A few miscellaneous commits to tidy up:
- `packaging: west is no longer a namespace package`
- `tree-wide: add python file copyright headers`
- `tests: enable coverage testing for plain 'tox'`

Housekeeping: miscellaneous things

---

.shippable.yml

This new pool uses large nodes and suitable for anything that does not
run sanitycheck. The queue for this pool is not as a long as with the
2XL pool which will give west instant results instead of waiting for 2XL
node to finish sanitycheck.

ci: move west to a different node pool

---

src/west/commands/project.py
src/west/manifest.py
tests/conftest.py
tests/test_manifest.py
tests/test_project.py

~DNM, depends on these housekeeping pull requests:~
- https://github.com/zephyrproject-rtos/west/pull/351 (now merged)
- https://github.com/zephyrproject-rtos/west/pull/352 (now merged)
- https://github.com/zephyrproject-rtos/west/pull/353 (now merged)
The commit log for the final commit sums this up pretty well:
```
Add additional line coverage for manifest.py using output from pycov.
I'm pretty happy with the resulting level of statement coverage (94%)
and the number of bugs that got shaken out by writing these (5 real
ones along with a couple of other improvements).
The remaining 6% is mostly trivial or part of the unimplemented
functions needed to import maps. The trivial stuff can get addressed
some other day if we're interested in getting to 100%, but I think
it's time to move on to …
```

Manifest and west init bug fixes and test cases

---

src/west/app/project.py
src/west/commands.py
src/west/manifest.py
tests/test_project.py

DNM, depends on https://github.com/zephyrproject-rtos/west/pull/363
This pull request covers some remaining work in manifest imports:
- git repository remote names match west manifest remote names on clone again 
- we allow west update on projects defined in the manifest repository, even if there are imports
- don't update projects twice when we've already done so via imports

Manifest import tweaks

---

src/west/app/project.py

This does a better accounting of update-related work.
It also cleans up the 'cloning and initializing' output line since it's not really what's going on, and people are likely to get confused about why it's so fast to clone repositories, then so slow to fetch from them, when in fact what's going on is that we're just initializing a local repository then fetching the remote.

(Low priority) more west update --stats

---

src/west/app/project.py
tests/test_project.py

Fixes: #374
This commit ensures that west topdir always prints in posix style and
thus fixes an issue in windows where CMake fails to parse the path when
'\' is used as separator.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

topdir: west topdir prints posix style path.

---

src/west/version.py

Includes a 'west topdir' change needed to make zephyr's use of this
command work properly.

West 0.7.1

---

src/west/manifest.py

Fixes: #378
When Zephyr is also the manifest repository then west fails to identify
ZEPHYR_BASE correctly as the project name is manifest, with path zephyr.
Therefore, before checking projects with path `zephyr` we first check if
the manifest repository has path == zephyr.
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

zephyr base: Fixes issue with failing to discover Zephyr base

---

src/west/app/project.py

Fixes: #380 
I've tested the following matrix of west updates:
{descendant branch checked out + dirty tree,
detached head + dirty tree,
branch checked out + clean tree,
detached descendant HEAD + clean tree}
x
{default behavior,
--keep-descendants,
--rebase}
And the output always warns when something surprising happens. The win is mostly due to removing the --quiet from the 'git checkout --detach' and letting git do the work for us.
I want to backport these changes to 0.7.2, so I'm intentionally preserving the existing --keep-descendants behavior. We can defer changes to that to 0.8.0 pending resolution of https://github.com/zephyrproject-rtos/west/issues/381.

Fix update verbosity

---

src/west/commands.py
src/west/manifest.py

The import feature is printing spurious warnings for duplicated west extensions if the user imports a manifest *and* gives a west-commands that the imported manifest already declares. Fix it.
See commit log for the second patch for a detailed example.

Fix west command duplicate warnings

---

MAINTAINERS.rst

A few process changes from doing a point release, mainly that we'll
cut an alpha release instead of an RC. That's being done because
uploading an alpha is something a maintainer can just do, without
having to go through the usual "bump version.py" review process. This
makes it easier to do things like testing over the weekend.

MAINTAINERS.rst: some changes from going through this once

---

src/west/app/project.py
src/west/log.py

depends on https://github.com/zephyrproject-rtos/west/pull/390

Output improvements

---

src/west/app/project.py

This prints the absolute path of the manifest file:
west manifest --path
Requested by @SebastianBoe

west manifest: add --path action

---

src/west/app/project.py
src/west/manifest.py

Some new flake8 errors are enabled by default now; fix them up:
```
./src/west/manifest.py:1633:47: E741 ambiguous variable name 'l'
./src/west/app/project.py:802:21: F541 f-string is missing placeholders
```

lint: flake8 fixes

---

.gitignore
src/west/commands.py
src/west/log.py
tox.ini
tox_deps.txt

These changes introduce initial support for type hints. Support for mypy
static analysis on GitHub workflows has also been enabled.
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>

west: initial support for type hints

---

src/west/app/main.py

Changing the comment, as we now officially support direct use of
WestApp().
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>
---- 
This PR is needed by: https://github.com/zephyrproject-rtos/zephyr/pull/26060
in order to correctly render the `WestApp` api.

app: make the WestApp class and the run method public API

---

src/west/app/main.py

This reverts commit 5843eef713fe28ab58885f5537f38a5604368212. We
figured out another way to accomplish the goal that this was done for,
so there's no reason to expose these details to the user now.

Revert "app: make main() in west.app.main module public API"

---

src/west/app/project.py
src/west/commands.py
src/west/configuration.py
src/west/manifest.py
src/west/util.py
tests/test_config.py
tests/test_manifest.py

Fixes: #273 
This makes west's internal representations for paths use pathlib objects whenever relevant or convenient. In particular, this is useful whenever path comparisons are necessary, since pathlib handles the canonicalization properly.
It also makes west accept os.PathLike in its public APIs in addition to str. This is consistent with the general direction of the python standard library and just generally reasonable practice for python in 2020.
I'm leaning pretty heavily on the type checker to catch my mistakes here. It definitely helped during development.
I tried to make this as symlink friendly as I could, but I can't say with 100% honesty that running west commands from `/some/symlink/to/a/workspace` doesn't ever leak the physical path behind the symlink.
Now that we are …

Overhaul path handling

---

src/west/app/main.py
tests/conftest.py
tests/test_project.py

Consider the following situation:
1. `m` is the manifest repository, `p` is a project
2. `m/west.yml` imports `p` at revision `rbad`; `p/west.yml` at `rbad` contains an invalid manifest
3. user runs `west update`, setting `p`'s `manifest-rev` to `rbad` (and failing the update)
4. user updates `m/west.yml` to point at `p` revision `rgood`, which contains good manifest data
5. user runs `west update` again
The `west update` in the last step should fix `p`'s manifest-rev, pointing it at `rgood`, and should succeed.
It doesn't, because west refuses to run `update` and just allows the command to crash because there was no valid manifest data, leaving the workspace in an unusable state: even though the top-level manifest points at a valid configuration, you can't run west update, or list, or …

Make sure west update can be used to recover from a bad import

---

src/west/app/main.py
src/west/app/project.py
src/west/manifest.py
tests/conftest.py
tests/test_project.py

Backports https://github.com/zephyrproject-rtos/west/pull/415 to v0.7-branch. I will begin the MAINTAINERS.rst process for getting v0.7.3 with this fix out as soon as time permits (current focus is on other tasks).
Tack on a couple more commits: one to to get past CI, another because it's a trivial fix

Backport recovery from bad import

---

MAINTAINERS.rst

Minor tweaks from testing the 0.7.3 release:
- mention Fedora as a Linux distro as as I've received reports of
active west users on that distro
- update board name for nrf52 board

MAINTAINERS.rst: updates following 0.7.3

---

src/west/version.py

The main purpose of this release is to get 877d46c ("app: fix import
error followed by update") out into users' hands. We've only received
one report of this happening in the wild so far, but it's an important
enough bug to cut a point release for.
Test report:
SHA a88d26b928116a8c6999d2d6dbac7f68590f25de is version `0.7.3a1` on PyPI.
Alpha release prepared and uploaded to PyPI as:
```
git checkout a88d26b928116a8c6999d2d6dbac7f68590f25de
git clean -ffdx
WEST_VERSION=0.7.3a1 python3 setup.py sdist bdist_wheel
twine upload -u zephyr-project dist/*
```
tox passes with `WEST_SKIP_SLOW_TESTS=0` on:
- macOS Catalina 10.15.3 (bare metal, Python 3.8.5, pip 20.2.1)
- Ubuntu 18.04 (docker, Python 3.6.9, pip 9.0.1)
- Ubuntu 20.04 (docker, Python 3.8.2, pip 20.0.2)
- Debian buster (docker, Python …

West v0.7.3

---

src/west/__main__.py
tests/test_main.py

This allows west to be executed as a module with "python3 -m west".
This can be useful if it's desired to execute west under a particular
Python interpreter, e.g. the same one that's used elsewhere in a
larger system.

add __main__.py

---

src/west/manifest.py
tests/test_manifest.py

If `Manifest.from_file(topdir=<topdir>)` is called with topdir then
Manifest is instantiated with topdir, source_file, and manifest_path.
However, if Manifest.from_file() is called without providing
topdir, then Manifest is instantiated with topdir and source_file only.
This causes the path to manifest repo to become None in later calls and
results in: https://github.com/nrfconnect/sdk-zephyr/pull/341
This is now fixed by ensure `manifest_path` is used for instantiating
Manifest class when using Manifest.from_file().
Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

manifest: adding manifest_path to kwargs when calling Manifest.__init__

---

tox.ini

We no longer need to filter based on the platform like this. Our tests
know what to do at runtime and so should our CI.

tox.ini: remove useless cruft

---

src/west/manifest.py

- ImportFlag: Sphinx output isn't really what I want it to be for this class. Fix it up.
- SCHEMA_VERSION: there are incompatible changes since last release

manifest: fix ImportFlag docstring for sphinx, bump schema version

---

src/west/version.py

We've forked a v0.8-branch branch for releasing that version, push
master ahead.

version: bump master branch to 0.8.99

---

src/west/app/project.py
tests/test_project.py

This isn't working properly without resolving the manifest directory.
Fixes: #435

init: fix 'west init -l .'

---

src/west/app/project.py

Let's make it clearer what happens in this case.
For the sake of not making the command line help too long, let's drop
the point that it can't be combined with -m or --mr and just make it
clear that -l doesn't use MANIFEST_URL. People will find out right
away if they try it that it doesn't work if they combine these
options.

Improve west init -l docs

---

src/west/manifest.py
tests/manifests/invalid_absolute_project_path.yml
tests/manifests/invalid_project_path_escapes.yml
tests/test_manifest.py

Let's use a lexical check instead of escapes_directory(). This
continues to let some users who are symlinking outside the workspace
to keep doing that, even though we don't officially support it in
west.
Also throw in a check for an absolute project path, which should never
happen and is similarly a sign of an attempt to escape the workspace.

manifest: rework workspace escape checks

---

src/west/manifest.py
tests/test_manifest.py

This provides alternatives to the racially laden terms `whitelist`,
used for a list of imports which are included, and `blacklist`, used
for a list of imports which are excluded with `includelist` and
respectively `excludelist`.

replace whitelist/blacklist with includelist/excludelist

---

src/west/manifest.py
tests/test_manifest.py

A manifest like this is not well-formed:
```yaml
manifest:
projects: [...]
self:
path:
```
Currently the `Manifest` parser accepts this data and gives back a `None` value in `self.projects[MANIFEST_PROJECT_INDEX].path`, which is wrong. The entire manifest should just be rejected as ill-formed.

An empty "self: path:" is an error

---

src/west/app/project.py

Print the git commands on their own lines to make them more visible.
Suggested-by: Joakim Andersson <joakim.andersson@nordicsemi.no>

update: tweak _post_checkout_help

---

setup.py

this adds support for running python ~/path/to/west/setup.py develop
from other directories.
Signed-off-by: Jacob Siverskog <jacob@teenage.engineering>

setup.py: support development mode from other directories

---

src/west/app/main.py

if running with invalid version (for instance newer than current
west), print (more) user-friendly error such as:
FATAL ERROR: west v1.0 or later is required by the manifest
West version: v0.8.99
Manifest file: west/west.yml
Please upgrade west and retry.
instead of:
File "west/src/west/app/main.py", line 172, in handle_builtin_manifest_load_err
assert args.command not in no_manifest_ok
AssertionError
Signed-off-by: Jacob Siverskog <jacob@teenage.engineering>

app: print error instead of assert

---

setup.py
src/west/app/config.py
src/west/app/project.py
src/west/configuration.py
src/west/manifest-schema.yml
src/west/manifest.py
src/west/version.py
tests/conftest.py
tests/test_config.py
tests/test_manifest.py
tests/test_project.py

The purpose of this pull request is to allow projects to declare groups they belong to, like this:
```yaml
manifest:
projects:
- name: foo
groups:
- YouAreIt
- name: bar
groups:
- YouAreIt
- MeToo
- name: baz
```
The above projects have these groups lists:
- foo: ['YouAreIt']
- bar: ['YouAreIt', 'MeToo']
- baz: []
Paired with this is a new top-level `update-groups` key in the manifest, which lets you specify allowlists and blocklists for groups:
```yaml
manifest:
groups:
- some-group
- another-group
no-groups:
- not-this-one
```
By default, `west update` will no longer update any project whose group is blocked (if there is a `no-groups` blocklist), or not explicitly allowed (if there is a `groups` allowlist). Allowlists override blocklists: if a project is blocked and allowed, it will be …

Project groups

---

src/west/app/project.py
src/west/manifest-schema.yml
src/west/manifest.py
tests/test_project.py

The submodules were added to the manifest in order to enable updating projects submodules when performing update operation.
Description of the `west update` command behaviour regarding submodules:
* Submodules can be defined in the west manifest file for the specific project, by adding submodules: field.
* Submodules field is not required for every project and should be added only if it is desired.
* Submodules field may have boolean values (true/false) or be the list of specific submodules.
* Assigning false value to the submodules field means that submodules are not used for given project. Example presented below:
- name: example_project
submodules: false
* Assigning true value to the submodules field means that all submodules attached by git to the project repository will be updated. …

update: add support for git submodules in west update.

---

src/west/app/project.py
src/west/manifest.py
tests/test_manifest.py
tests/test_project.py

During review of the documentation for the 0.9 release, the following changes to manifest groups were requested:
- groups should be 'enabled' and 'disabled', not 'allowed' or 'blocked'
- enabling a group should be done by prefixing its name with '+'  in "manifest: groups:" or manifest.groups
Projects are still 'active' or 'inactive'.

Additional changes for west 0.9

---

src/west/manifest.py
src/west/version.py

This branch is now moving independently of v0.9-branch.

Bump versions for post-0.9 development

---

src/west/manifest.py
src/west/version.py

This is a new version of west with incompatible schema changes, so we
have to bump west.manifest.SCHEMA_VERSION in addition to what's in
version.py.

Bump versions for 0.9 release

---

src/west/commands.py

Python environments usually do not import importlib.util
unless asked to do so specifically:
>\>\>\> import importlib
>\>\>\> importlib.util
>Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>AttributeError: module 'importlib' has no attribute 'util'
Therefore it would be better to import importlib.util explicitly.
Some commands (e.g. west zephyr-export) do not work on my setup
without that change.
Signed-off-by: Ilya Tagunov <tagunil@gmail.com>

commands: import importlib.util explicitly

---

src/west/app/project.py
src/west/manifest-schema.yml
src/west/manifest.py
tests/test_manifest.py
tests/test_project.py

As a result of review of the project groups feature documentation, change some of the names to be more clear, and be a bit more forgiving in the error handling.
A project's 'groups' list remains the same. No changes there.
However, we make the following changes:
- 'manifest: groups:' is now 'manifest: group-filter:'
- we add a west.manifest.Manifest.group_filter value, exposing 'manifest: group-filter:' after validation and string conversion
- the config option 'manifest.groups' is now 'manifest.group-filter'
- invalid values in manifest.group-filter are downgraded to warnings
- the west update '--groups' option becomes '--group-filter', with a slightly shorter name '--gf' if you can't handle that
I tacked on another fixup to the tests I noticed.

Group filters

---

src/west/manifest-schema.yml

This is stale from before the move to group-filter and changing its
semantics to requiring a + and -.

manifest-schema.yml: fix a comment

---

src/west/manifest.py
tests/test_project.py

2 commits, see commit messages
Forcing users to define something unused is not just tedious, it's also confusing.

manifest: make optional the 'name' attribute unused by Submodule

---

src/west/manifest.py
tests/test_project.py

2 plain cherry-picks.
Related to doc update https://github.com/zephyrproject-rtos/zephyr/pull/32106

manifest: make optional the 'name' attribute unused by Submodule (0.9 backport)

---

src/west/__init__.py
src/west/manifest-schema.yml
src/west/manifest.py
src/west/version.py
tests/manifests/invalid_no_projects.yml
tests/test_manifest.py

The west 0.9 documentation for group-filter states:
Only the top level manifest file’s manifest: group-filter:
value has any effect. The manifest: group-filter: values in any
imported manifests are ignored.
See [Project Groups and Active Projects](https://docs.zephyrproject.org/latest/guides/west/manifest.html#project-groups-and-active-projects) for details on this feature.
This turns out to have been a mistake, which we are reversing course on.
It's a mistake because all users who import a manifest which makes some projects inactive will have to also manually disable the same groups just to get the same default list of projects.
Example manifest fragments showing the issue:
```yaml
manifest:
projects:
- name: upstream
import: true
```
and:
```yaml
manifest:
group-filter: …
```

Import group filters, too

---

src/west/app/project.py
tests/test_project.py

Thanks to @marc-hb for pointing me in the right direction on this `ls-remote` incantation.
Instead of hard-coding a default revision to fetch from the remote,
get it from the remote URL itself if it's not provided by the user.
If that fails, we ask for the --manifest-rev option to be provided
explicitly.
This makes the code more robust by making its behavior match git
clone, which checks out whatever the remote wants you to use by
default instead of making assumptions.

west init: get default manifest-rev from remote

---

src/west/app/project.py
src/west/version.py
tests/test_project.py

Backport the 'west init --manifest-rev' change from master which
queries the remote for its HEAD branch if that option is not given.
Required for Zephyr to move its 'master' branch to 'main' without
breaking a plain 'west init'.

West v0.10.1a1

---

src/west/manifest.py

Submodule was single-quoted (``) causing reference errors.

manifest: fix docstrings for Project

---

src/west/app/project.py

Silences the following, verbose and repetive warning when using
git >= 2.28
As this warning is 10 lines long and there are 40 projects in zephyr
right now, this cuts stderr for `west init` almost in half, from ~950
lines down to ~550 lines.
The non @static-ness of the git methods explained in PR #494 has to
"leak" to ensure_cloned(), at least for now. A single Update object
downloads all projects so this does not cause git --version to be
invoked many times.
```
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen …
```

project.py: --initial-branch=placeholder to silence verbose warning

---

src/west/app/project.py

Sync submodules by default

---

src/west/version.py

No manifest schema changes; SCHEMA_VERSION 0.10 is correct.

West 0.11.0a1

---

src/west/commands.py
tests/test_commands.py

I ran into this testing 0.11.0a1. Our current code matches against the
last word in the 'git --version' output. Unfortunately, for 'git
version 2.24.3 (Apple Git-128)', that's incorrectly matching against
'Git-128)', which doesn't work.
Generalize the version detection a bit to handle this.

commands: fix git version detection on macOS

---

src/west/app/project.py
tox.ini

When a project revision in west.yml is a lightweight tag,
'git cat-file -t <revision>' prints 'commit' instead of 'tag'.
Hilarious as this may be, it confuses the _rev_type() helper used by
west update. The helper doesn't know what kind of revision it is,
since it's not a branch and doesn't look like a commit either. We then
fetch the tag unnecessarily since we don't know what we're dealing
with. That works, but we don't need to hit the network in this case.
Fix this by handling the lightweight tag case as well.

west update: fix --fetch=smart for lightweight tags

---

MAINTAINERS.rst
README.rst
src/west/app/project.py
src/west/manifest-schema.yml
tests/conftest.py

The main point of this PR is to fix an issue where initializing from a URL leaves the manifest repository in a detached HEAD state. 
To get here, though, I needed to include other fixes so I could test it on my Arch machine, which is no longer passing tox, due to changes in the way git works.
While I'm here, I decided to grep for 'master' throughout the tree and remove it where possible or no longer applicable, to keep up as much as practical with where git is going in the time I have to work on this. I'm leaving some work for the future; see commit logs for details.

Detached HEAD in manifest repository and master fixes

---

src/west/manifest.py

Fixes: #523
The Manifest class has these instance attributes:
- _projects_by_name: maps project names -> Projects, has 'manifest' as
a key and the ManifestProject as a value (this is one reason why
'manifest' is a reserved project name)
- _projects_by_rpath: maps resolve()d Paths -> Projects, has the
manifest repository's path as a key, pointing to the ManifestProject
So get_projects() ought to just rely on these dicts to do its job.
However, it's currently got extra special-case code it doesn't need,
and the code is buggy. Specifically this part:
mpath: Optional[Path] = Path(mp.path).resolve()
This is trying to get the ManifestProject's resolved path, but it only
works if you happen to be in the workspace topdir, since mp.path is
relative.
We got "lucky" and can still find the manifest …

manifest: simplify and fix get_projects()

---

tests/conftest.py

Commit 6d42388
("tests: adjust create_repo() to keep working on newer git") got tox
working again in Arch on my laptop, and in CI for whatever GitHub
decides to use for ubuntu-latest, but it breaks tox on my Ubuntu 20.04
LTS testing environment that I use for release testing.
Fix it, again, and hopefully for the last time. See comments in the
source code for details on the fix.

Fix checkout -b in conftest

---

src/west/version.py

New features:
- west status now only prints output for projects which have a nonempty
status.
Bug fixes:
- The manifest file parser was incorrectly allowing project names which contain
the path separator characters / and \. These invalid characters are
now rejected.
Note: if you need to place a project within a subdirectory of the workspace
topdir, use the 'path:' key. If you need to customize a project's fetch URL
relative to its remote 'url-base:', use 'repo-path:'.
- The changes made in west v0.10.1 to the 'west init --manifest-rev' option
which selected the default branch name were leaving the manifest repository
in a detached HEAD state. This has been fixed by using 'git clone' internally
instead of 'git init' and 'git fetch'. See issue #522 for details.
- The WEST_CONFIG_LOCAL …

West 0.11.1

---

src/west/manifest-schema.yml
src/west/manifest.py
tests/test_manifest.py

Add a new optional 'userdata' key to projects.
The value will be parsed and stored in the userdata attribute of the
corresponding west.manifest.Project object.
Example manifest file:
```yaml
manifest:
projects:
- name: foo
- name: bar
userdata: a-string
- name: baz
userdata:
key: value
defaults:
remote: r
remotes:
- name: r
url-base: base
```
Example Python usage:
```py
manifest = west.manifest.Manifest.from_file()
foo, bar, baz = manifest.get_projects(['foo', 'bar', 'baz'])
print(foo.userdata) # None
print(bar.userdata) # prints 'a-string'
print(baz.userdata) # prints {'key': 'value'}
```

manifest: add project 'userdata' key (was: metadata)

---

src/west/manifest.py
tests/test_manifest.py

Make sure the userdata round-trips properly through 'west manifest
--freeze' by adding it to the project's dict representation.
Add a missing repr() inside the userdata related part of
Project.__repr__.
Fixes: #536

manifest: fix some Project.userdata issues

---

src/west/app/project.py

For 'git fetch', neither --tags nor --no-tags is the default value. The
default value is a middle ground that fetches "any tag that points into
the histories being fetched is also fetched" - second paragraph in "git
help fetch". Rather than duplicating this relatively non-intuitive git
help in such a small space, be completely transparent about what the
west code does and lead the reader to the original git documentation.
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

update: fix --tags explanation in --narrow help string

---

src/west/manifest.py
tests/test_manifest.py

The addition of project userdata was a breaking change for older
versions of west. This means we should have bumped the schema version
when it was added, but this was missed. Do it now.

Bump schema version

---

src/west/app/project.py

If a project has created a tag or branch with the name HEAD (which
they really shouldn't do) it will cause the command:
'git rev-parse --abbrev-ref HEAD' to fail to provide a ref.
Check if 'git rev-parse --abbrev-ref HEAD' fails to return a value and
if so do a `log.die()` rather than failing at the 'git merge-base'
stage with a less useful error.
Closes #561

Raise RuntimeError() if can't find rev for HEAD

---

src/west/app/config.py
src/west/app/main.py
src/west/app/project.py
src/west/commands.py
src/west/configuration.py
src/west/manifest.py
tests/test_help.py
tests/test_manifest.py

This is basically a prep work PR which:
- helps us out with #149 
- lays the groundwork for resolving some longstanding TODOs and ugly/buggy code within the west.manifest subpackage

Add west.configuration.Configuration class

---

src/west/app/main.py
src/west/app/project.py
src/west/manifest.py
tests/manifests/invalid_duplicate_name.yml
tests/test_manifest.py
tests/test_project.py

Fixes: #572 
This is an API break. We are still allowed to do that until west 1.0.
The west.manifest.Manifest class's path handling has become
unmaintainable and we need to overhaul it. The from_data() and
from_file() constructors are too clever and try to allow too many use
cases, which results in the guts of the manifest construction code
often not being able to tell whether it's in a real workspace or not.
This makes it difficult to know when we can safely read configuration
files or not. That in turn makes it difficult to accurately
distinguish between the 'manifest.path' value in the local configuration
file and the 'self: path:' value in the manifest data, especially when
we can take keyword arguments that say "hey, pretend this is your
path".
Additionally, there are a few …

Overhaul manifest path handling

---

src/west/manifest-schema.yml
src/west/manifest.py
tests/test_manifest.py

The purpose of this PR is to allow for specifying userdata in the manifest repository. One of the primary reasons I am making the switch from the Google repo tool to the Zephyr west tool is to allow for specifying the firmware version information using the userdata capability in the manifest file. I also wanted to be able to combine my manifest repository with my project repository. I soon discovered that userdata is allowed for projects but excluded for no seemingly good reason for the manifest repository.

Allow userdata to be defined under self in manifest repository

---

src/west/manifest.py
tests/test_manifest.py

Without a file argument, we should still use fall_back=True to search
for the workspace in the environment. This behavior was removed in the
recent rework of path handling, introducing a regression where the
manifest repository cannot be found when outside the workspace. Fix
it.

manifest: fix Manifest.from_file() with fall_back

---

src/west/configuration.py
src/west/manifest.py
tests/test_manifest.py

Commit c757d6650f7df5e3950b704dd756241a9c84a352
("configuration: add Configuration class") was part of a general
re-work of how configuration file handling went.
As part of this change, an internal _whence() method was added, which
returns a list of configuration file paths on the file system for a
given ConfigFile enumerator. _whence() is currently erroring out with
a RuntimeError() when a local configuration file is requested, but not
found.
This breaks error handling in some cases.
For example, consider a flow like this:
```
$ west init
$ west list
```
It would be better to raise MalformedConfig from here instead. This
lets higher layers handle this error better. In the above case,
we now get this instead:
```
$ west list
FATAL ERROR: can't load west manifest
local configuration file …
```

Fix configuration error

---

src/west/app/main.py

Commit 2327610945323390cc330d23938d3c50a6f596c6
("manifest: ManifestImportFailed: relax argument specification")
changed the attributes in ManifestImportFailed instances, but the
corresponding error handling code in main.py was not updated.
This is incorrect and results in an ugly traceback instead of a
properly formatted error message.
Restore the preferred behavior by using the new attribute 'imp'.
Fixes: #588

main: update ManifestImportFailed error handling

---

src/west/app/main.py

Be clearer about what happened when we lack permissions to load the
manifest, but we need to do so in order to proceed. This can happen,
for instance, if it is owned by another user and read access is
denied.
Fixes: #579

main: handle PermissionError

---

src/west/app/config.py

Verify that the user-provided option name contains a '.' before passing it off to API functions that require that.
Fixes: #600

config: validate option name

---

src/west/configuration.py

Fixes #600
De-duplicate the `option.split('.', 1)` "parsing" code into a new,
minimalistic and centralized `_InternalCF.key_parse` function. Add two
lines of error handling in this new function in order to provide a
meaningful error message instead of this cryptic and context free exception
when using a "build_board" key name without a dot:
```
...
File "/usr/lib/python3.10/site-packages/west/configuration.py", in _get
section, key = option.split('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```
The API user now gets this:
```
...
File "/usr/lib/python3.10/site-packages/west/configuration.py", in parse_key
raise ValueError(f"Invalid key name: '{dotted_name}'")
ValueError: Invalid key name: 'build_board'
```
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

configuration: fix error handling of keys missing a '.'

---

src/west/app/project.py
src/west/commands.py
tests/test_project.py

Fixes: #619 
The user-visible fix is in `update: add --submodule-init-config option`: this allows users to clone submodules on a case-by-case basis using `west update --submodule-init-config protocol.file.allow=always ...` without having to globally change their git configuration to allow this unsafe protocol to be used everywhere.
The other fixes are for our CI and are due to fallout from the git change discussed in #619 and one other unrelated mypy issue.

Fix submodule file protocol error

---

src/west/app/main.py

This prevents python's argparse library from allowing it to generate its own shortened command line options which can cause problems when commands are added in future with similar names to existing arguments.
Not tested with tox since it does not seem to want to run on my PC for some reason, not even in a new virtual environment.

main.py: Prevent shortened command line arguments

---

src/west/app/project.py

Since west v0.11.1, this must be a branch or tag name.

init: clarify --manifest-rev help string

---

src/west/log.py

The message is only printed if the ``level`` parameter is _lower or equal to_ (not "at least) the current verbosity level.
We need a "sign errors" joke similar to this one:
https://www.martinfowler.com/bliki/TwoHardThings.html
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

log.py: minor log level pydoc fix

---

MANIFEST.in
setup.py

The west package contains type annotations, but mypy doesn't know about them because of a missing metadata file. This prevents us from type-checking calls into the west APIs, which we should be able to do.
Add the necessary metadata to make this work.

add typing information

---

tests/test_project.py

The goal of this PR is to add a regression test for #545.
I'm starting with a regression test that I think captures all the cases:
- a project with `submodules: true`
- a project with `submodules: <list-of-mappings>`
- a submodule with both `name:` and `path:`
- a submodule with only `path:`
- a submodule with submodules of its own
All submodule paths are relative. The test is currently failing as expected and is marked xfail as such.
I'm hoping to get some confirmation that this addresses the problem and I haven't missed any use cases as the discussion in the issue is quite long at this point.

Regression test for submodules with relative paths

---

src/west/log.py

I'd like to call the next west release 1.0, with accompanying stability guarantees, so the deprecation timeline for west.log needs to move to v2.0 to satisfy semantic versioning.

west.log: defer removal date

---

src/west/app/project.py
tests/conftest.py
tests/test_project.py

This was requested by a user in a comment in issue #144. The purpose is to make it easy to run commands on interesting subsets of projects in a convenient way.
See help text for details.

forall: add --group argument

---

src/west/app/main.py

For missing files, the new output looks like this:
FATAL ERROR: manifest file not found: /home/mbolivar/zp/zephyr/nosuchfile
Please check manifest.file and manifest.path in /home/mbolivar/zp/.west/config
The old output looks like this:
FATAL ERROR: file not found: /home/mbolivar/zp/zephyr/nosuchfile
The new output is clearly more helpful.
Make a similar improvement for permission errors.

app: improve manifest load errors

---

src/west/manifest.py

The rationale is to avoid requiring users to use 'version: 0.13' in their manifest files now that west 1.0 has been released. We should have done this in time for west 1.0.0, but that ship has sailed. We can, and will, backport this to the release that becomes v1.0.1, though.

manifest: bump SCHEMA_VERSION to 1.0

---

src/west/app/main.py
src/west/manifest.py
src/west/version.py

Backport https://github.com/zephyrproject-rtos/west/commit/9789617cd5becaf2b7d75aee996e9e3477cbc4a2 to the release branch. I don't think it's worth bothering with going through the entire testing procedure in an "alpha" 1.0.1a1 release as described in MAINTAINERS.rst since this is an isolated change that has been tested in its own right.

West v1.0.1

---

src/west/app/main.py
src/west/app/project.py
tests/test_project.py

Help text for the new command:
```
$ west help compare
usage: west compare [-h] [-a] [--exit-code] [--ignore-branches] [PROJECT ...]
Compare each project's working tree state against the results
of the most recent successful "west update" command.
This command prints "git status" output for a project if
(and only if) at least one of the following is true:
1. its checked out commit is different than the commit checked
out by the most recent successful "west update"
2. its working tree is not clean (i.e. there are local uncommitted
changes)
3. it has a local checked out branch
positional arguments:
PROJECT            projects (by name or path) to operate on; defaults to active cloned projects
options:
-h, --help         show this help message and exit
-a, --all          include output for …
```

West compare command

---

src/west/app/main.py
src/west/manifest.py

The default west manifest file in zephyrproject-rtos/zephyr recently added a project with an 'import'.
That means that 'west build' will fail with the confusing 'invalid choice: "build"' error if you pull zephyr without running 'west update'. This is a worse experience than what happens when you run e.g. 'west list': running a built-in command that needs the manifest to do its work will happily tell you you need to run 'west update' to resolve the failed import.
This is confusing people who pull and run 'west build', and we do have enough information to do better from WestArgumentParser.error(), which is the official argparse callback API invoked when parse_known_arguments() fails in this situation.
Extract the error message formatting for this situation into a helper function and use it …

main: handle ManifestImportError from extensions better

---

src/west/configuration.py

Also rename internal parameter `search_for_local` to `find_local`. `search_for_local` is easier to misinterpret as optional (not finding a local file is fatal when True).

configuration.py: clarify Configuration constructor's behavior

---

src/west/app/project.py

When a project is not on the `manifest-rev` it will often be on a branch or tag. Use the `%d` format to make `west compare` show that information.
As discussed in #643 and before, git status cannot be fully trusted to display branch information.
Sample new output:
```
west compare
=== zephyr (zephyr):
--- manifest-rev: e40859f78712 (some_tag) Revert "dma: dw: Do ...
HEAD: e803b77463b4 (zephyrproject/main) samples: net: ...
--- status:
HEAD detached at zephyrproject/main
nothing to commit, working tree clean
```

compare: add --decorate

---

src/west/app/main.py
src/west/app/project.py
src/west/manifest.py
tests/test_manifest.py

Take three at trying to provide an "import filtering" (#543) solution that will work to allow making the bsim project in zephyr/west.yml inactive, so you can `west build` etc without it cloned.
To test:
```
west init zephyrproject
cd zephyrproject
west list # error because bsim project has 'import' and is not cloned
west config manifest.project-filter -- -bsim
west list # works, and bsim project is not in the output (it's inactive)
west list bsim # works, prints the usual info for bsim
```
alternatively:
```
west config --global manifest.project-filter -- -bsim
west init zephyrproject
cd zephyrproject
west list # works
```
------
Add support for a new manifest.project-filter configuration option.
The option's value is a comma-separated list of regular expressions,
each prefixed with '+' …

`manifest.project-filter`

---

src/west/app/main.py
src/west/app/project.py
src/west/commands.py
tests/test_project.py

This has been requested various times, but its lack never bothered me up until now, etc. Anyway, here it is.
Fixes: https://github.com/zephyrproject-rtos/west/issues/337
```
EXAMPLES
--------
To get "git grep foo" results from all cloned, active projects:
west grep foo
To do the same with:
- git grep --untracked: west grep --untracked foo
- ripgrep:              west grep --tool ripgrep foo
- grep --recursive:     west grep --tool grep foo
To switch the default tool to:
- ripgrep:  west config grep.tool ripgrep
- grep:     west config grep.tool grep
GREP TOOLS
----------
This command runs a "grep tool" command in the top directory of each project.
Supported tools:
- git-grep (default)
- ripgrep
- grep
Set the "grep.tool" configuration option to change the default.
Use "--tool" to switch …
```

commands: add grep

---

src/west/app/project.py

Fixes commit 1d220bbd627b ("commands: add grep") / #678 
Fix misplaced closing parenthese in:
```python
shlex.split(self.config.get(f'grep.{tool}-args'), '')
```
The empty string is meant as a default value for config.get() but it was passed as a second argument to shlex.split() by mistake.
Funny enough this hangs forever:
```python
>>> shlex.split(None, comments='')
<stdin>:1: DeprecationWarning: Passing None for 's' to shlex.split() is deprecated.
(hangs forever)
```
PS: debuggers rulez

grep: fix command hanging forever when grep.{tool}-args is empty

---

src/west/app/project.py

This detection would ideally occur before the lengthy clone operation, but `manifest_path` is derived from the files retrieved...
EDIT: see newer commit message

west manifest: detect when target directory already exists, and fail

---

README.rst
tox.ini

The tox indirection layer is convenient except for the usual problems
caused by too many layers of indirection:
- Add some examples and show how it is still possible to use important
pytest features. This is also useful to boost people familiar with
Python but not with pytest.
- To stop developers wasting their time trying, document a major
limitation with the current approach: impossible to run the west
code in a debugger when it's started from a test.
- Show how the "printf" alternative can work.

README.rst: add pytest examples and mention tox limitations

---

src/west/app/project.py

It's not unusual to make "quick and dirty", temporary changes in a git
repo that is on the manifest: either add some untracked files or create
a branch. As expected, this makes the repository show in `west compare`.
If such repos and the manifest repo are the only repos
appearing in the `west compare` output, then no manifest-rev + HEAD
banner ever appeared. When no banner ever appears it's really not
obvious which repos are on the manifest-rev vs not. In other words: the
main `west compare` feature is defeated.
Clear this doubt by always showing the banner, even when `HEAD` and
`manifest-rev` are the same. See sample output below.
I think the original design idea was to follow diff's "spirit" not to
show anything that's identical and to save as many lines as
possible. However I don't …

compare: always prefix `git status` output with manifest-rev

---

src/west/app/project.py
src/west/manifest.py
tox.ini

For convenience, Project.git() supports passing either a list (good) or a string with whitespaces (bad). The latter is parsed with shlex.split()
This saves some typing but the caller has to be extremely careful to never use the shlex.split() convenience with unsanitized inputs.
Fixes commit 3ac600acaa11 ("git: clean west ref space after fetching") where the caller was not careful and concatenated `update-ref -d ` with unsanitized input, possibly containing special characters as found in bug #679. Fix this bug by converting the string to a list.
While at it, look for a few other, frequent and risky invocations and convert their string argument to a list too. The following test hack was used to semi-automate the search for these other locations:
```diff
--- a/src/west/manifest.py
+++ …
```

Project.git(list/str): reduce reliance on shlex.split()

---

src/west/version.py

This is not a west release. It is just a signal that we have forked off v1.2-branch.

version: 1.2.99

---

src/west/commands.py

When interpreted as restructured text, these are causing errors because the '**' is interpreted as the start of a bold section, which never ends. This causes build failures in the zephyr docs, which do treat these as RST.
Wrap them in `` to make the whole thing a literal block to fix this issue.

commands: fix some docstrings

---

src/west/commands.py

Giant commit
https://github.com/zephyrproject-rtos/hal_nxp/commit/f9f0944bc2b4fce "Update to SDK 2.14" added files with malformed UTF-8, more precisely with the DEGREE SIGN (°) encoded in 8bit latin1/CP1252.
This crashes `west grep`.
Before this fix:
```
nxp$ west grep 'TEMPERATURE_CONV_FACTOR.*Will give'
Traceback (most recent call last):
File ".local/bin/west", line 33, in <module>
sys.exit(load_entry_point('west', 'console_scripts', 'west')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "west/src/west/app/main.py", line 1085, in main
app.run(argv or sys.argv[1:])
File "west/src/west/app/main.py", line 244, in run
self.run_command(argv, early_args)
File "west/src/west/app/main.py", line 503, in run_command
self.run_builtin(args, unknown)
File "west/src/west/app/main.py", …
```

Use 'backslashreplace' not to crash on malformed UTF from subprocess

---

src/west/app/project.py

There have been many users reports in #558 that `west init` fails on the Windows NTFS filesystem when some IDEs are running concurrently.
There is no simple and reliable fix for this because:
- The lack of concurrency is a core limitation in the NTFS design that will not change anytime soon,
- IDEs have no reliable way to know when they should pause scanning the filesystem.
- Placing temporary files outside the workspace would invite other, complex and nasty issues with cross-filesystem moves (#558)
Short of a fix, explain why this happens very briefly in `west init -h` and request users to temporarily close their IDEs. It's the only simple and universal mitigation available.
Mention the issue number in case someone needs more details, some evidence or smarter workarounds specific to …

project.py: request users to stop IDEs before running `west init`

---

src/west/app/project.py
tests/test_project.py

This extends cache support for submodules using git --reference flag. I also tested whether reference flag could be used instead of local clone as described here: https://github.com/zephyrproject-rtos/west/issues/625 but that was slower than using local clone.

Extend cache support for submodules

---

.github/workflows/test.yml

Long overdue; both where still at @v1!
Found by chance in
https://github.com/zephyrproject-rtos/west/actions/runs/9275086435/job/25518959121?pr=711 where all macos-latest configs failed like this:
```
Run actions/setup-python@v1
Error: Version 3.8 with arch x64 not found
Available versions:
(empty)
```

.github: upgrade to checkout@v4 and setup-python@v5

---

src/west/app/project.py
src/west/manifest.py

3 commits.
- Two de-duplication commits with no effect
- Consistently decode manifests with utf-8
This is a "larger" alternative to #710

Always decode manifests with utf-8; not just most of the time

---

src/west/app/project.py
tests/test_project.py

Add an argument to the west diff command that allows to set the manifest revision as the merge-base.

app: project: Allow to diff against manifest revision

---

src/west/app/project.py
src/west/manifest.py
tests/test_project.py

Add environment variables when running forall for each project.

app: project: Improve forall

---

src/west/app/project.py
tests/test_project.py

`west` should pass unknown arguments to `git status` and `git diff` commands.
This allows things like:
```shell
$ west status --short --branch
$ west diff --stat
```

app: Allow passing arguments to git status/diff

---

src/west/app/main.py

Commit d84237108992 ("app: handle unexpected command name better") intentionally created a big error handling difference between extensions and built-in commands. As an unfortunate side effect, it lost the relevant "manifest import failure" error messages for _extension_ commands.  This is especially ironic when the extension command is missing because the import failed, see example in #726.
Error handling is generally very hard to test comprehensively and even more so in this complex "bootstrap" area. Rather than trying to refactor it once again, tweak the existing error messages to gently steer the user away from (potentially missing) extensions and towards built-in commands that provide a simpler and better error handling out of the box: they still show relevant, manifest error …

app: point "handle_unknown_command()" error message to "west -vv status"

---

.github/workflows/test.yml
tests/conftest.py
tests/test_project.py
tox.ini

3 commits. main one:
Stop using `shlex.split()` in conftest.py as a way to prepare test
commands for subprocess.run() because it does not always work. When we
have quoting issues, just avoid them entirely by passing the test
command as a list.
Replace shlex.split() with a simple str.split() for convenience in
simple cases. This simple split() will immediately fail when trying to
use quote which is working exactly as intended.
This also makes the cmd() interface more similar to subprocess.run() and
its many friends, which is good thing.
This is similar to commit https://github.com/zephyrproject-rtos/west/commit/41007648d993b84144bbab54a26ac3416e2aef1d ("Project.git(list/str): reduce
reliance on shlex.split()") but applied to tests/
Before commit …

tests: stop using shlex.split() and use lists instead

---

src/west/app/main.py
src/west/commands.py
src/west/log.py

Add a west argument to set verbosity to the quiet mode

app: Add -q argument for quiet mode

---

src/west/app/main.py
tests/test_alias.py

This PR allows to add `alias` west commands to a configuration, similar to how git aliases work.
It can override existing commands to have default arguments, and iteratively replace alias commands.
Some examples:
```shell
$ west config --global alias.run "build --pristine=never -t run"
$ west config --global alias.menuconfig "build --pristine=never -t menuconfig"
$ west config alias.my_proj "build -b native_sim samples/hello_world -- -DCONFIG_ASSERT=y"
$ west config alias.build "build --pristine=always"
```
After applying you can run:
```shell
$ west run         #> west build --pristine=always --pristine=never -t run
$ west menuconfig  #> west build --pristine=always --pristine=never -t menuconfig
$ west my_proj     #> west build --pristine=always -b native_sim samples/hello_world -- …
```

app: support alias commands

---

src/west/app/main.py
src/west/commands.py

It seems natural to recommend "debug" flags when telling the user to "debug".
More specifically, this makes a big difference in situations like the one reported in #671

app: tell the user to use `-vv` when debugging "manifest --validate"

---

README.rst

This section was outdated as we have moved to pyproject.toml.

README.rst: Update installing from source section

---

src/west/manifest.py
tests/conftest.py
tests/manifests/invalid_submodule_no_path.yml
tests/test_manifest.py
tests/test_project.py

Submodules were missing when calling --freeze or --resolve
Fixes #739

manifest: Add submodule representation in as_dict

---

.gitignore
MAINTAINERS.rst
docker-testing/README.rst
docker-testing/arch/Dockerfile
docker-testing/compose.yaml
docker-testing/debian/Dockerfile
docker-testing/fedora/Dockerfile
docker-testing/in-container-test.sh
docker-testing/run-tests.sh
tox.ini

Updated #687 as it appeared to be stale, but still useful.

Add docker compose based test environment for Linux

---

.github/workflows/package.yml
.github/workflows/release.yml
.github/workflows/test.yml
MAINTAINERS.rst

Add Github workflows to create Pypi packages and upload to Pypi when a release is published.

.github: Pypi release workflows

---

src/west/app/project.py
tests/test_project.py

Although `clone-depth` is provided to use for `update` command, the `--depth` option is not provided for `init` without `-l`. It adds this option.

Add option to specify git clone options like --depth for Zephyr repo clone via init

---

src/west/app/project.py
tests/test_project.py

Fixes new `west diff --manifest` option added by commit 0d5ee4eb0834 ("app: project: Allow to diff against manifest revision")
Do not pass `project.revision` to `git diff` because `project.revision` is unresolved user input and does not always resolve to a commit. For instance, `project.revision` can be the name of a remote branch like `v3.7-branch` that does not exist locally; then `git diff` fails. Or even worse: there could be a local branch of the same name which points to a totally different commit.
This bug was found when discussing issue #747, see 7th comment there for a longer description of what `manifest-rev` is and how it works.

project.py: fix west diff --manifest to use `manifest-rev`

---

.github/workflows/release.yml

- Add more details on parts of the steps.
- Cherry-picked 02e05ff to fix pypi uploads in the future

.github: Update release workflow

---

.github/workflows/package.yml
.github/workflows/test.yml
pyproject.toml
src/west/manifest.py

Python 3.8 is end-of-life, removed.
Python 3.13 is released, added.

.github: Update supported python versions

---

src/west/app/project.py
src/west/configuration.py
src/west/manifest.py
src/west/util.py
tests/manifests/invalid_project_in_west_dir.yml
tests/manifests/invalid_project_in_west_reldir.yml
tests/manifests/invalid_project_in_west_relsubdir.yml
tests/manifests/invalid_project_in_west_subdir.yml

It's not allowed to have projects inside the .west directory, add a check when parsing the manifest.
Fixes #102

manifest: Do not allow projects inside the west directory

---

src/west/commands.py

Print a stack trace when debugging with -vvv or more. This is MUCH faster than `git grep error_message` and it's even more useful when the same error message is used in multiple places! Example: die_already() in project.py

commands: make die() print a stack trace when -vvv or more

---

.github/workflows/test.yml
src/west/configuration.py
tests/conftest.py
tests/test_config.py
tests/test_project.py

Make deprecated calls explicit during testing or remove them if unnecessary.
This allows us to promote warnings to errors with `pytest`.

tests: Wrap or remove deprecated functions

---

src/west/manifest.py
tox.ini

- Fix errors for: E721 Use `is` and `is not` for type comparisons.
- Add `ruff check` to tox.

project: Add ruff check to tox

---

pyproject.toml
src/west/app/main.py
src/west/app/project.py
src/west/commands.py
src/west/configuration.py
src/west/manifest.py
src/west/util.py
tests/test_manifest.py
tests/test_project.py

Depending on the minimum supported python version (3.9 in our case), `pyupgrade` will report deprecated python features.
Extend `ruff` with `pyupgrade` checks.
Depends on #762

project: Fix and check pyupgrade issues

---

pyproject.toml
src/west/app/config.py
src/west/app/main.py
src/west/app/project.py
src/west/commands.py
src/west/configuration.py
src/west/log.py
src/west/manifest.py
tests/conftest.py
tests/test_alias.py
tests/test_config.py
tests/test_help.py
tests/test_manifest.py
tests/test_project.py

Apply `isort --profile black` on files in `src/` and `tests/`

project: Format and sort imports

---

pyproject.toml
src/west/app/config.py
src/west/app/main.py
src/west/configuration.py
src/west/manifest.py
tests/test_project.py

Enable pycodestyle, flake8-bugbear, pyflakes rules when running ruff check.

project: Extend ruff check with pycodestyle, flake8-bugbear, pyflakes

---

src/west/app/config.py

Use builtin mutually exclusive group support instead of a custom action.

app: config: Mutually exclusive group for local/global/system argument

---

.github/workflows/format.yml
pyproject.toml
tox.ini

Prevent ruff issues being reported by updates of the tool itself.
UP027 has been removed in version 0.8.0, remove it from the ignore list.
For CI move the `continue-on-error` to the format step instead of the job. This should set the job status to green, we only print a notice annotation.
See #771 how the result looks.

project+ci: Succeed ruff format check but keep a notice annotation

---

src/west/app/config.py
tests/test_config.py

In some cases, and specifically in the manifest.group-filter and manifest.project-filter options, it is sometimes useful to be able to append to a value instead of replacing it completely.
For example, assuming one wants to add to an existing group filter, without this patch the user needs to do:
(assuming the group filter is currently +unstable,-optional, and the
user wants to add +extras).
$ west config manifest.group-filter
$ west config manifest.group-filter +unstable,-optional,+extras
With this patch instead:
$ west config -a manifest.group-filter ,+extras

app: config: Add support for appending to the config string

---

tests/conftest.py
tests/test_config.py

Dedent assertion checks as they were currently skipped, and make sure the correct error message is validated.
Fixes #776

tests: config: Fix assertions checks with pytest.raises

---

src/west/app/config.py

A user has pointed out that west's behavior in the following case is confusing:
```
west config foo.bar=baz
```
The desired behavior is "set foo.bar to baz". Instead, west exits 1 without printing anything on the console.
Let's make it clearer that the user is inadventently asking for the value of an option called "foo.bar=baz", since right now there is no rule forbidding "=" in option names, so the above confusing case is actually asking for section "foo", key "bar=baz".
With this patch, west prints:
```
ERROR: foo.bar=baz is unset
```
to stderr along with exiting 1, making it clearer that something went wrong.

config: upgrade dbg to err on missing option

---

tests/test_project.py

This test is meant to cover the handling of duplicate command names, including the warnings to be emitted. Previously, it only tested the case where two extension commands had the same name. The other case is duplicating a built-in command name, which prompts a different warning message, so update the test to include it.
Additionally, ensure that each duplicate command in the test comes from a different project, so that each warning message is expected to contain a different project name. This serves to verify the bug fix from commit edd1cee2ebb6191cb6fa4ec874d0113c1fd2b9a3.

tests: Extend test_extension_command_duplicate

---

.github/workflows/scorecards.yml

Introduce a workflow to run analysis on this repository as recommended by the OpenSSF guidelines.
Copied from https://github.com/zephyrproject-rtos/zephyr/blob/c60ffe1e1bcab71fce9d9bb06c2c0db7fe0fe17c/.github/workflows/scorecards.yml

.github: Add scorecards workflow

---

.github/workflows/codeql.yml
.github/workflows/release.yml

- Add code analysis tool CodeQL as a workflow to scan github actions and python code.
- Add top-level `read` permission to the release workflow.

.github: Add CodeQL workflow and update top-level permissions

---

src/west/app/project.py
tests/test_project.py

This new command-line switch implements something similar to `git
status`'s untracked files display.
The code examines the workspace and prints out all files and folders
that are not inside of a west project.
Fixes: #622
Supersedes #702

app: manifest: Add the ability to display untracked files and directories

---

pyproject.toml
src/west/app/main.py
src/west/commands.py

Some variables were declared with either `nonlocal` or `global` but never assigned any value in their scope.
Fixes #797

app/commands: Remove unused `nonlocal/global` declarations

---

.codecov.yml

Code coverage with CodeCov is still a work in progress, do not block PRs.

project: Report coverage in PRs without blocking

---

README.rst
pyproject.toml

Display the supported Python versions and CodeCov coverage on the README page.
Note: The python version badge will be updated once released on Pypi.

README: Add badges for Python and CodeCov

---

src/west/app/project.py
src/west/manifest.py
tests/test_project.py

EDIT: The discussions in #491 and #667 made it clear that `--freeze` and `--resolve` should not have their behavior changed.
Updated the PR to introduce `--active-only` for `--resolve/--freeze`.
~~Running `west manifest --freeze` expects projects to be cloned, but the purpose of inactive projects is to not clone these explicitly.~~
~~Currently it's not possible to call `west manifest --freeze` on a clean zephyr installment because of the `optional` projects.~~

manifest: Support --active-only argument for --resolve/--freeze

---

pyproject.toml

West does not depend on setuptools, this is only a build requirement.

project: Drop setuptools dependency

---

pyproject.toml

Coverage subprocess has been removed in pytest-cov 7.0. To migrate the `patch` option has to be added.
See https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html
@marc-hb the [coverage](https://app.codecov.io/gh/zephyrproject-rtos/west) plummeted to 48% for no apparent reason because, in CI, we simply install the latest versions of all tools. 
As it took quite some time to figure this out, I intend to come back to locking dependency versions in CI. But with a better proposal, stay tuned.

repo: Patch coverage with subprocess

---

pyproject.toml

[PEP 639](https://peps.python.org/pep-0639/) describes how packages should improve license clarity. Add an SPDX license string alongside the LICENSE file reference.
See: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files

pyproject.toml: Update license info for PEP 639
